const browserPrivacy = "Choosing a file does not upload its contents to PDFArrow. Processing runs in this browser, and the result is downloaded directly to this device.";

export const HIGH_INTENT_TOOL_CONTENT = Object.freeze({
  "edit-pdf": {
    seoTitle: "Edit PDF Online Free — Text, Images, Shapes | PDFArrow",
    metaDescription: "Edit a PDF online for free. Change text overlays, add text, images, shapes, highlights, signatures, and download the finished PDF privately.",
    heroHeadline: "Edit a PDF directly in your browser",
    heroSubheadline: "Change supported text, add content, mark up pages, and download a finished copy without installing software or creating an account.",
    longDescription: "PDFArrow opens valid PDFs in a full browser editor with page thumbnails, zoom, search, text tools, images, drawing, shapes, signatures, and page controls. Unchanged native PDF content remains intact during export; added content is flattened so it displays consistently in standard PDF readers.",
    benefits: ["Edit and annotate up to 500 pages with progressive rendering.", "Add text, images, shapes, checks, signatures, highlights, and drawings.", "Download without an account or a PDFArrow watermark."],
    steps: ["Choose a valid, unencrypted PDF or start with a blank page.", "Select a toolbar control, place the change exactly where it belongs, and adjust it on the page.", "Review every changed page, then download and reopen the exported PDF."],
    useCases: ["Correcting a document before sending it", "Completing and signing a form", "Adding visual notes to a PDF"],
    verificationChecklist: ["Zoom in on every changed area and confirm that new content is aligned.", "Search or select unchanged text to confirm native page content remains usable.", "Reopen the downloaded file in a second PDF reader before sharing it."],
    privacySummary: browserPrivacy,
    troubleshooting: [
      { question: "Why can’t I select text in a scanned PDF?", answer: "A scanned page is an image, not native PDF text. Run OCR first, or place a new text box over the page." },
      { question: "Why does a font look slightly different?", answer: "The original embedded font may not be available to the browser. Use the closest available font and verify line wrapping before export." },
      { question: "Why won’t my PDF open?", answer: "Confirm that it is a valid PDF under 50 MB, has no more than 500 pages, and is not encrypted or password protected." },
    ],
    faqEntries: [
      { question: "Can I edit a PDF online for free?", answer: "Yes. Supported editing tools work in the browser without an account, subscription, or PDFArrow watermark." },
      { question: "Can PDFArrow edit existing PDF text?", answer: "It can replace supported extracted text overlays while preserving the rest of the page. Complex fonts, unusual encodings, and scanned text may require adding a new text box or using OCR." },
      { question: "Does editing upload my PDF?", answer: browserPrivacy },
      { question: "What is the maximum PDF size?", answer: "The editor accepts valid, unencrypted PDFs up to 50 MB and 500 pages. Device memory can still affect unusually complex documents." },
      { question: "Will the downloaded PDF have a watermark?", answer: "No. PDFArrow does not add a branding watermark to supported exports." },
    ],
  },
  "merge-pdf": {
    seoTitle: "Merge PDF Files Online Free and Privately | PDFArrow",
    metaDescription: "Merge up to 20 PDF files in your chosen order. Combine native PDF pages privately in your browser without signup or a watermark.",
    heroHeadline: "Merge PDF files in the exact order you choose",
    heroSubheadline: "Combine native PDF pages without turning them into screenshots, then download one high-fidelity document.",
    longDescription: "The merge workflow copies complete pages from each source PDF into one output file. Page dimensions, rotation, vector artwork, selectable text, and embedded page content are retained instead of rasterizing every page.",
    benefits: ["Drag files into the final order before merging.", "Preserve native page dimensions, text, vectors, and rotation.", "Combine up to 20 PDFs and 200 total pages locally."],
    steps: ["Add at least two valid, unencrypted PDF files.", "Drag the files into the required order and confirm the total page count.", "Download the merged PDF and verify its first, last, and transition pages."],
    useCases: ["Combining an application packet", "Joining monthly reports", "Adding attachments to a main document"],
    verificationChecklist: ["Confirm the final page count equals the total shown before merging.", "Check the page where each source document begins and ends.", "Select text and test links on representative pages when those features matter."],
    privacySummary: browserPrivacy,
    troubleshooting: [
      { question: "Why is a file rejected?", answer: "The file must be a valid, unencrypted PDF no larger than 50 MB. The combined selection can contain up to 20 files and 200 pages." },
      { question: "Why is the merged file large?", answer: "Merging preserves source page content and does not automatically compress images. Use Compress PDF afterward if a smaller file is more important than preserving interactivity." },
      { question: "Can I change the order?", answer: "Yes. Drag files in the list before downloading; every PDF keeps its internal page order." },
    ],
    faqEntries: [
      { question: "How many PDFs can I merge?", answer: "You can combine up to 20 valid PDFs, 50 MB per file, with a maximum of 200 pages in the merged output." },
      { question: "Does merging reduce PDF quality?", answer: "No rasterization is used during merging. Native pages are copied into the result so their original visual quality is retained." },
      { question: "Can I rearrange PDFs before merging?", answer: "Yes. Drag each file into the exact order you want before creating the output." },
      { question: "Are merged files uploaded?", answer: browserPrivacy },
      { question: "Can I merge password-protected PDFs?", answer: "Not directly. Remove a password first only when you know it and are authorized to modify the document." },
    ],
  },
  "split-pdf": {
    seoTitle: "Split PDF by Page Ranges Online Free | PDFArrow",
    metaDescription: "Split a PDF into separate files by page range. Preview pages, enter ranges, and download native PDF output privately without signup.",
    heroHeadline: "Split a PDF into the page ranges you need",
    heroSubheadline: "Preview the document, enter one or more ranges, and download separate high-fidelity PDFs in a ZIP file.",
    longDescription: "PDFArrow parses comma-separated page ranges and copies the selected native pages into separate PDF files. Text, vectors, page dimensions, and rotation are retained because the pages are not converted to images.",
    benefits: ["Preview page numbers before defining ranges.", "Create several separate PDFs in one operation.", "Preserve native page content in every split file."],
    steps: ["Choose a valid, unencrypted PDF and review its page previews.", "Enter comma-separated ranges such as 1-3, 4-6, 7.", "Download the split files and confirm each filename and page range."],
    useCases: ["Separating chapters from a handbook", "Extracting individual invoices", "Dividing a large submission into sections"],
    verificationChecklist: ["Confirm every requested source page appears in one intended output.", "Open the first and last page of each split PDF.", "Check the ZIP contains the expected number of files."],
    privacySummary: browserPrivacy,
    troubleshooting: [
      { question: "What range format should I use?", answer: "Use inclusive page numbers separated by commas, for example 1-3, 4-6, 7. Page numbering starts at 1." },
      { question: "Why is my range invalid?", answer: "Remove duplicate punctuation and make sure every page number is between 1 and the document’s final page." },
      { question: "Why did I receive a ZIP?", answer: "Multiple ranges create multiple PDFs, so they are packaged together in one ZIP download." },
    ],
    faqEntries: [
      { question: "Can I split a PDF into multiple files?", answer: "Yes. Each comma-separated range becomes a separate PDF, and multiple results download together as a ZIP." },
      { question: "Does splitting change page quality?", answer: "No. Selected native PDF pages are copied into new documents without rasterizing them." },
      { question: "What PDF limits apply?", answer: "The browser workflow supports valid, unencrypted PDFs up to 50 MB and 200 pages." },
      { question: "Can I extract just one page?", answer: "Yes. Enter a single page number as its own range, such as 7." },
      { question: "Does PDFArrow store the split PDF?", answer: browserPrivacy },
    ],
  },
  "compress-pdf": {
    seoTitle: "Compress PDF Online Free — Reduce PDF Size | PDFArrow",
    metaDescription: "Batch compress PDFs online with measured savings, side-by-side previews, structure-preserving modes, and optional maximum visual compression.",
    heroHeadline: "Compress a PDF without flattening its features",
    heroSubheadline: "Reduce one PDF or a batch locally, compare the first page, and see measured savings before using the result.",
    longDescription: "Balanced and Lossless cleanup rewrite PDF streams and objects without rendering pages, keeping selectable text, links, forms, vectors, and page structure. Maximum reduction is an explicit fallback that flattens pages to lower-quality JPEG images. Batch results are measured individually and downloaded together.",
    benefits: ["Preserve PDF features with the default Balanced setting.", "Compare original and compressed first pages.", "Batch up to 20 PDFs and download only results that are actually smaller."],
    steps: ["Choose one or more valid, unencrypted PDFs.", "Select Lossless cleanup, Balanced, or Maximum reduction.", "Review measured savings and the visual preview, then reopen the downloaded result."],
    useCases: ["Meeting an email attachment limit", "Reducing a scanned application", "Preparing a smaller upload copy"],
    verificationChecklist: ["Compare the original and compressed file sizes.", "Check selectable text, links, and form fields when using a structure-preserving level.", "Revalidate any cryptographic signature after compression and keep the signed original."],
    privacySummary: browserPrivacy,
    troubleshooting: [
      { question: "Why isn’t the compressed PDF smaller?", answer: "Already optimized or mostly text-based PDFs may not benefit from image re-rendering. PDFArrow will not offer a larger result as a successful compression." },
      { question: "Will compression keep text and forms?", answer: "Balanced and Preserve quality keep selectable text, links, forms, vectors, and document structure. Maximum compression flattens pages and should only be used when the smallest visual copy matters most." },
      { question: "Why does small text look soft?", answer: "Stronger compression lowers page resolution and JPEG quality. Choose a higher-quality setting or retain the source document." },
    ],
    faqEntries: [
      { question: "How does PDFArrow compress a PDF?", answer: "Balanced and Preserve quality compact PDF objects and streams without rendering pages. Maximum compression re-renders pages only when you explicitly choose the flattened visual fallback." },
      { question: "Will compression preserve selectable text?", answer: "Yes in Balanced and Preserve quality modes. Maximum compression flattens pages and removes selectable text and interactive features." },
      { question: "Will every PDF become smaller?", answer: "No. Text-based and already optimized files may not shrink. The app only offers the new download when it is smaller." },
      { question: "Is PDF compression free?", answer: "Yes. The supported browser workflow does not require signup or add a watermark." },
      { question: "Is the PDF uploaded for compression?", answer: browserPrivacy },
    ],
  },
  "pdf-to-word": {
    seoTitle: "Convert PDF to Word Online — Editable DOCX | PDFArrow",
    metaDescription: "Convert PDF to Word with editable layout reconstruction, direct OCR for scanned pages, or visual fidelity. Download DOCX privately in your browser.",
    heroHeadline: "Convert PDF to Word with editable or visual output",
    heroSubheadline: "Choose editable reconstruction when you need reusable text or visual fidelity when matching the source page matters most.",
    longDescription: "Editable mode reconstructs text into DOCX paragraphs while retaining page breaks, order, indentation, spacing, common font styling, and approximate page proportions. Visual fidelity mode places a high-resolution page image in the DOCX so the document looks closer to the PDF but is not fully editable.",
    benefits: ["Choose editable layout, direct scanned-page OCR, or visual fidelity.", "Preserve page breaks, common styling, and tab-aligned columns in editable mode.", "Process unencrypted PDFs locally without an Office or AI upload."],
    steps: ["Choose a text-based, unencrypted PDF.", "Select editable reconstruction or visual fidelity based on how you will use the DOCX.", "Open the result in Word or another DOCX editor and check layout, fonts, and reading order."],
    useCases: ["Reusing text from a finished PDF", "Making small revisions in Word", "Keeping a visual PDF copy inside DOCX"],
    verificationChecklist: ["Compare headings, paragraphs, lists, and page breaks with the source PDF.", "Check tables, columns, and text boxes carefully because PDF reading order can be ambiguous.", "Use visual fidelity mode or OCR when editable reconstruction is unsuitable."],
    privacySummary: browserPrivacy,
    troubleshooting: [
      { question: "Why is the Word file not editable?", answer: "Visual fidelity mode uses page images. Choose editable reconstruction when you need paragraph text." },
      { question: "Can I convert a scanned PDF?", answer: "Yes. Choose Scanned PDF — editable OCR and select the document language. PDFArrow recognizes image-only pages directly and places the recovered text into the Word file." },
      { question: "Why did columns move?", answer: "PDF stores positioned page elements rather than Word’s document structure. Complex columns, tables, and floating elements require review after reconstruction." },
    ],
    faqEntries: [
      { question: "Can I convert PDF to an editable Word document?", answer: "Yes. Editable mode reconstructs extracted PDF text as DOCX paragraphs, although complex layout should always be reviewed." },
      { question: "What is visual fidelity mode?", answer: "It places each PDF page as a high-resolution image in Word, preserving appearance better but limiting text editing." },
      { question: "Does PDF to Word work on scanned files?", answer: "Yes. Scanned PDF — editable OCR recognizes image-only pages directly in six supported languages. Visual fidelity mode is also available when exact page appearance matters more than editing." },
      { question: "What limits apply?", answer: "Conversion supports valid, unencrypted PDFs up to 20 MB and 50 pages." },
      { question: "Is my PDF sent to Microsoft or an AI service?", answer: "No. The supported conversion runs locally and does not upload the file to Microsoft, an OCR service, or an AI service." },
    ],
  },
  "word-to-pdf": {
    seoTitle: "Convert Word to PDF Online — Searchable PDF | PDFArrow",
    metaDescription: "Convert DOCX to a visually faithful, searchable PDF in your browser. Preserve page appearance and selectable text without an Office upload.",
    heroHeadline: "Convert Word to a searchable PDF in your browser",
    heroSubheadline: "Render DOCX pages at high resolution and add a searchable text layer for a shareable fixed-layout result.",
    longDescription: "PDFArrow renders DOCX content into high-resolution PDF pages and adds an invisible text layer so supported words remain selectable and searchable. Macros and live Word fields are not executed, and exact appearance still depends on available browser fonts and supported DOCX layout features.",
    benefits: ["Create a fixed-layout PDF from DOCX without Microsoft Office.", "Keep supported text selectable and searchable.", "Process files locally without executing macros or live fields."],
    steps: ["Choose a modern DOCX file under the current size limit.", "Review the rendered page preview and start the conversion.", "Open the PDF and verify page breaks, fonts, images, and selectable text."],
    useCases: ["Sharing a final resume", "Sending a fixed-layout report", "Archiving a Word document as PDF"],
    verificationChecklist: ["Confirm the PDF page count and page breaks match the DOCX.", "Check substituted fonts, tables, headers, footers, and positioned images.", "Search for a known phrase to verify the text layer."],
    privacySummary: browserPrivacy,
    troubleshooting: [
      { question: "Why is my .doc file rejected?", answer: "The converter supports modern DOCX files. Open a legacy .doc in Word or LibreOffice and save it as .docx first." },
      { question: "Why did a font change?", answer: "A document font unavailable in the browser must be substituted. Review line wrapping and page breaks in the result." },
      { question: "Are macros executed?", answer: "No. Macros and live Word fields are intentionally not executed during browser conversion." },
    ],
    faqEntries: [
      { question: "Can I convert DOCX to PDF without Microsoft Word?", answer: "Yes. PDFArrow performs supported DOCX rendering in the browser and creates a downloadable PDF." },
      { question: "Is the PDF searchable?", answer: "Yes. Supported rendered text receives an invisible searchable layer so it can be selected and found in standard PDF readers." },
      { question: "Are legacy .doc files supported?", answer: "No. Save the document as DOCX before using this converter." },
      { question: "What limits apply?", answer: "DOCX files up to 20 MB and 50 rendered pages are supported." },
      { question: "Is my Word file uploaded?", answer: browserPrivacy },
    ],
  },
  "ocr-pdf": {
    seoTitle: "OCR PDF Online — Make Scans Searchable | PDFArrow",
    metaDescription: "Run OCR on scanned PDFs in six languages. Clean pages, detect orientation, and download a searchable PDF plus TXT locally in your browser.",
    heroHeadline: "Make a scanned PDF searchable with local OCR",
    heroSubheadline: "Clean page images, correct orientation, recognize six languages, and download both a searchable PDF and extracted text.",
    longDescription: "The OCR workflow downloads the selected recognition model, renders and cleans each page, recognizes text locally, and creates a searchable image PDF plus a TXT file. Confidence reporting identifies results that deserve closer review.",
    benefits: ["Recognize six supported document languages.", "Apply automatic cleanup and orientation correction.", "Download a searchable PDF, TXT file, and confidence summary."],
    steps: ["Choose a clear, unencrypted scanned PDF and select its main language.", "Choose cleanup and orientation settings, then run OCR on this device.", "Review low-confidence names, dates, and numbers before using the searchable output."],
    useCases: ["Searching scanned agreements", "Copying text from paper records", "Making an image PDF easier to archive"],
    verificationChecklist: ["Search for several known words in the downloaded PDF.", "Compare important names, dates, amounts, and identifiers with the scan.", "Review low-confidence text and retain the original scan as the source of truth."],
    privacySummary: "The selected language model is downloaded on first use, but the PDF pages and recognized text are processed on this device and are not sent to an OCR or AI service.",
    troubleshooting: [
      { question: "Why is OCR inaccurate?", answer: "Blur, shadows, handwriting, low resolution, skew, and the wrong language reduce accuracy. Try a clearer scan, automatic cleanup, and the correct language." },
      { question: "Why does OCR take time?", answer: "Recognition runs page by page on your device. The first use also downloads the selected language model." },
      { question: "Why is handwriting not recognized well?", answer: "This workflow is optimized for printed text. Handwriting requires careful manual review and may not produce reliable text." },
    ],
    faqEntries: [
      { question: "What does OCR do to a PDF?", answer: "OCR recognizes text in page images and adds a searchable text layer while keeping the scan visible." },
      { question: "Which OCR languages are supported?", answer: "The current workflow offers English, Spanish, French, German, Italian, and Portuguese recognition." },
      { question: "Can OCR recognize handwriting?", answer: "It is designed for printed text. Handwriting and poor scans may produce unreliable results and require correction." },
      { question: "What limits apply?", answer: "Browser OCR supports unencrypted PDFs up to 20 MB and 24 pages." },
      { question: "Is OCR performed by an external service?", answer: "No. A language model downloads on first use, then recognition and PDF creation run on this device." },
    ],
  },
  "sign-pdf": {
    seoTitle: "Sign PDF Online Free — Type, Draw, or Upload | PDFArrow",
    metaDescription: "Sign a PDF online by typing, drawing, or uploading a signature. Place it precisely and download the signed copy privately without signup.",
    heroHeadline: "Sign a PDF exactly where the signature belongs",
    heroSubheadline: "Type, draw, or upload your signature, position it on the page, and download a self-signed copy without creating an account.",
    longDescription: "The self-signing workflow creates a visual signature from typed text, freehand drawing, or an uploaded image. You control its exact page position and size before it is flattened into the downloaded PDF for consistent display.",
    benefits: ["Type, draw, or upload a signature image.", "Move and resize the signature directly on the PDF page.", "Add initials and dates before downloading a flattened copy."],
    steps: ["Choose a valid PDF and create a typed, drawn, or uploaded signature.", "Place and resize the signature on the correct page; add dates or initials if needed.", "Review the complete document and download the self-signed PDF."],
    useCases: ["Self-signing an authorization form", "Adding initials to an acknowledgement", "Placing a signature and date on an agreement"],
    verificationChecklist: ["Confirm the signature is on the intended page and line.", "Check that no signature or initial covers nearby text.", "Reopen the downloaded PDF and confirm every required field is visible."],
    privacySummary: browserPrivacy,
    troubleshooting: [
      { question: "Why is my uploaded signature background visible?", answer: "Use a transparent PNG for the cleanest result, or crop the image closely before uploading it." },
      { question: "Is this a digital certificate signature?", answer: "No. This tool places self-attested visual signature content; it does not issue a cryptographic certificate or verify identity." },
      { question: "Can I send this to someone else to sign?", answer: "Yes. Signed-in owners can create a revocable, expiring single-signer link with required fields. The recipient can type or draw a signature and download both the signed PDF and a device-generated SHA-256 completion receipt. Automated reminders and independent identity verification are not included." },
    ],
    faqEntries: [
      { question: "How can I create my signature?", answer: "Type your name, draw with a pointer or touchscreen, or upload a PNG or JPG signature image." },
      { question: "Is signing a PDF free?", answer: "Yes. The supported self-signing workflow requires no account and adds no PDFArrow watermark." },
      { question: "Is this a certificate-based digital signature?", answer: "No. It is a visual self-signature and does not provide certificate validation, identity verification, or a completion certificate." },
      { question: "Can I add initials and dates too?", answer: "Yes. The editor includes supported initials and date controls that are flattened into the export." },
      { question: "Is my signature uploaded?", answer: browserPrivacy },
    ],
  },
  "protect-pdf": {
    seoTitle: "Password Protect PDF with AES-256 Online | PDFArrow",
    metaDescription: "Protect a PDF with an AES-256 open password in your browser. Download an encrypted copy without sending the PDF or password to a server.",
    heroHeadline: "Protect a PDF with an AES-256 open password",
    heroSubheadline: "Encrypt an authorized PDF locally so readers must enter the password before opening the downloaded copy.",
    longDescription: "PDFArrow applies AES-256 password encryption in the browser and creates a new protected PDF. This controls opening the file; it does not provide enterprise rights management, password recovery, certificate encryption, or guaranteed control after an authorized reader opens it.",
    benefits: ["Apply AES-256 encryption without uploading the document.", "Require a password whenever the protected copy is opened.", "Keep the original file separate from the encrypted download."],
    steps: ["Choose a PDF you own or are authorized to protect.", "Enter and confirm a strong, unique open password, then create the encrypted copy.", "Close the PDF and test the downloaded file with the password before sending it."],
    useCases: ["Sending a confidential attachment", "Protecting a personal record", "Adding an opening password before storage"],
    verificationChecklist: ["Close all open copies and confirm the new PDF requests a password.", "Test the exact password in a second PDF reader.", "Store the password separately because PDFArrow cannot recover it."],
    privacySummary: "The PDF and password are used only in this browser to create the encrypted download. Passwords and document contents are not included in analytics.",
    troubleshooting: [
      { question: "Why can’t PDFArrow recover my password?", answer: "The password is not stored or transmitted. Keep it in a trusted password manager because losing it can make the protected copy inaccessible." },
      { question: "Does this stop screenshots or copying after opening?", answer: "No. An open password controls access to the file but cannot guarantee how an authorized reader uses visible content afterward." },
      { question: "Why should I test another PDF reader?", answer: "Testing confirms the encrypted output works in the software your recipient is likely to use." },
    ],
    faqEntries: [
      { question: "What encryption does Protect PDF use?", answer: "The browser workflow applies AES-256 encryption and requires the password before the protected PDF can be opened." },
      { question: "Does PDFArrow know my PDF password?", answer: "No. The password is used locally for encryption and is not included in analytics or sent to PDFArrow." },
      { question: "Can PDFArrow recover a forgotten password?", answer: "No. Store the password safely and keep an authorized unprotected source copy." },
      { question: "Does password protection prevent every type of copying?", answer: "No. It controls opening the encrypted file, not screenshots, photography, or every action after an authorized reader opens it." },
      { question: "Do I need an account?", answer: "No. The supported browser protection workflow can be used and downloaded without an account." },
    ],
  },
  "compare-pdf": {
    seoTitle: "Compare Two PDFs — Text and Visual Changes | PDFArrow",
    metaDescription: "Compare two PDFs side by side. Review additions, deletions, replacements, moved text, and focused visual changes, then download a report.",
    heroHeadline: "Compare two PDFs change by change",
    heroSubheadline: "Review searchable text differences and focused visual changes side by side instead of covering the entire page with detection boxes.",
    longDescription: "PDFArrow aligns corresponding pages, compares extracted words, groups nearby changes, and distinguishes additions, deletions, replacements, and moved text. Image-only pages use focused visual regions. A change navigator and scroll lock make each difference reviewable before report export.",
    benefits: ["See additions in blue and removals in red.", "Navigate individual replacements and moved-text changes.", "Download a marked PDF report after reviewing the comparison."],
    steps: ["Choose the original PDF on the left and the revised PDF on the right.", "Run the comparison, then use next and previous controls to review every detected change.", "Confirm meaningful changes against both source documents and download the report if needed."],
    useCases: ["Reviewing a revised contract", "Checking an updated policy", "Comparing two resume or report versions"],
    verificationChecklist: ["Review the change list instead of relying only on page tinting.", "Check moved paragraphs and layout changes against both source PDFs.", "Treat visual detections on scanned pages as review regions, not automatic conclusions."],
    privacySummary: "Both PDFs are rendered, analyzed, and compared in this browser. Their text and page images are not sent to a document-comparison or AI service.",
    troubleshooting: [
      { question: "Why does a scanned page show visual regions instead of word changes?", answer: "Image-only pages do not contain searchable text. The comparison uses focused pixel-difference regions unless OCR text is available." },
      { question: "Why are unchanged words sometimes marked?", answer: "Font substitution, reflow, scanning noise, or small positioning changes can alter extracted words or pixels. Review each detection against the source pages." },
      { question: "Is this the same as Word Track Changes?", answer: "No. It compares two final PDF versions and cannot reconstruct author names, edit timestamps, or the original document’s tracked-edit history." },
    ],
    faqEntries: [
      { question: "What changes can PDFArrow detect?", answer: "Searchable pages receive additions, deletions, replacements, and moved-text changes. Scanned or image-only pages receive focused visual difference regions." },
      { question: "Can I compare scanned PDFs?", answer: "Yes, but pages without searchable text use visual comparison. Running OCR first can provide more useful word-level changes." },
      { question: "What limits apply?", answer: "You can compare two valid, unencrypted PDFs up to 25 MB and 75 pages each." },
      { question: "Can I download the comparison?", answer: "Yes. After reviewing the results, you can download a marked PDF report." },
      { question: "Are the two PDFs uploaded?", answer: "No. Page rendering, text extraction, visual comparison, and report generation run in this browser." },
    ],
  },
});

export const HIGH_INTENT_TOOL_IDS = Object.freeze(Object.keys(HIGH_INTENT_TOOL_CONTENT));
