import { ROUTE_PATHS } from "../router/routePaths.js";
import { PRODUCT_LAST_TESTED_ISO, PRODUCT_LAST_TESTED_LABEL, PRODUCT_RESPONSIBLE_PARTY } from "./toolEvidence.js";
import { PDF_ATTACHMENT_SIZE_STUDY, SEARCH_GUIDES } from "./searchGuides.js";

const common = {
  reviewedIso: PRODUCT_LAST_TESTED_ISO,
  reviewedLabel: PRODUCT_LAST_TESTED_LABEL,
  owner: PRODUCT_RESPONSIBLE_PARTY,
};

const newGuideCommon = {
  ...common,
  publishedIso: "2026-07-29",
  reviewedIso: "2026-07-29",
  reviewedLabel: "July 29, 2026",
};

/** @param {string} label @param {string} path @param {string} description */
const toolLink = (label, path, description) => ({ label, path, description });

export const EDITORIAL_RESOURCE_PAGES = Object.freeze([
  {
    ...common,
    id: "resources",
    kind: "hub",
    path: ROUTE_PATHS.resources,
    eyebrow: "Original PDFEnrich resources",
    title: "PDF research, safety guides, and workflow playbooks",
    seoTitle: "PDF Research, Guides and Trust Center | PDFEnrich",
    metaDescription: "Read original PDF benchmarks, redaction and OCR guides, industry workflows, architecture notes, uptime, and incident history.",
    lede: "Useful material built from the same regression fixtures, browser workflows, and product boundaries used to release PDFEnrich tools.",
    facts: [
      ["Research standard", "Methods and downloadable fixtures"],
      ["Product evidence", "21 core workflows mapped to regression checks"],
      ["Editorial policy", "One strong page per real search intent"],
    ],
    sections: [
      { heading: "Research you can reproduce", body: "The quarterly conversion benchmark publishes its scope, test classes, known gaps, and sample files. A pass means the stated assertion passed; it is not a claim that every possible PDF will convert perfectly.", bullets: ["Download the same simple, complex, scanned, malformed, and large fixtures.", "See which output property each core tool verifies.", "Use the methodology to report a reproducible failure."] },
      { heading: "Safety guidance with proof", body: "The redaction and OCR guides focus on mistakes that can expose information or corrupt meaning. They include verification steps, not just button instructions.", bullets: ["Prove redacted text is absent from extracted content.", "Choose OCR settings based on scan quality and document type.", "Keep original source files when flattening or OCR changes document structure."] },
      { heading: "Operational transparency", body: "The trust center separates current architecture and controls from future plans. It does not imply an audit, certification, SLA, or incident-free history that PDFEnrich cannot substantiate." },
    ],
    related: [
      toolLink("Quarterly PDF benchmark", ROUTE_PATHS.pdfBenchmark, "Methodology, release results, and downloadable fixtures."),
      toolLink("Safe PDF redaction guide", ROUTE_PATHS.redactGuide, "A before-and-after proof workflow for removing hidden text."),
      toolLink("Scanned PDF and OCR guide", ROUTE_PATHS.ocrQualityGuide, "Settings and verification by scan quality and document type."),
      toolLink("How to edit a PDF", ROUTE_PATHS.editPdfGuide, "Choose the least invasive edit and verify the exported copy."),
      toolLink("How to compress a PDF", ROUTE_PATHS.compressPdfGuide, "Preserve the features you need and compare measured savings."),
      toolLink("How to combine PDF files", ROUTE_PATHS.combinePdfGuide, "Build an ordered packet and inspect every file transition."),
      toolLink("How to fill and sign a PDF", ROUTE_PATHS.fillAndSignPdfGuide, "Complete fields, place a visual signature, and verify the submission copy."),
      toolLink("PDF to Word formatting", ROUTE_PATHS.pdfToWordGuide, "Choose editable, OCR, or visual-fidelity conversion."),
      toolLink("PDF attachment size study", ROUTE_PATHS.pdfAttachmentSizeStudy, "Download measured raw and Base64-encoded fixture sizes."),
      toolLink("Edit a PDF on iPhone", ROUTE_PATHS.editPdfOnIphoneGuide, "Use the touch editor from Safari and verify the Files download."),
      toolLink("Edit a scanned PDF", ROUTE_PATHS.editScannedPdfGuide, "Decide whether the page needs OCR or a careful visual correction."),
      toolLink("Compress a PDF to 1 MB", ROUTE_PATHS.compressPdfToOneMbGuide, "Work toward a fixed byte ceiling without hiding quality loss."),
      toolLink("Compress a PDF for email", ROUTE_PATHS.compressPdfForEmailGuide, "Leave room for email encoding and message overhead."),
      toolLink("Combine PDFs on Mac", ROUTE_PATHS.combinePdfOnMacGuide, "Arrange native PDF pages and verify every file transition."),
      toolLink("Sign a PDF on Android", ROUTE_PATHS.signPdfOnAndroidGuide, "Place and verify a visual signature from a phone."),
      toolLink("Fill a PDF without Adobe", ROUTE_PATHS.fillPdfWithoutAdobeGuide, "Choose the right workflow for interactive or flat forms."),
      toolLink("PDF to Word without losing formatting", ROUTE_PATHS.pdfToWordWithoutFormattingLossGuide, "Choose editable text or visual fidelity deliberately."),
      toolLink("Remove pages from a PDF", ROUTE_PATHS.removePagesFromPdfGuide, "Delete the correct pages from a copy and verify the result."),
      toolLink("Rotate a PDF and save it", ROUTE_PATHS.rotatePdfAndSaveGuide, "Apply permanent page rotation instead of changing only the viewer."),
      toolLink("Security", ROUTE_PATHS.security, "Current safeguards, limitations, and reporting path."),
      toolLink("Architecture", ROUTE_PATHS.architecture, "Where document processing, identity, analytics, and storage run."),
    ],
  },
  {
    ...common,
    id: "pdf-conversion-benchmark",
    kind: "benchmark",
    path: ROUTE_PATHS.pdfBenchmark,
    eyebrow: "Q3 2026 browser PDF benchmark",
    title: "A reproducible benchmark for browser PDF fidelity and recovery",
    seoTitle: "Q3 2026 Browser PDF Conversion and Fidelity Benchmark | PDFEnrich",
    metaDescription: "Review PDFEnrich's Q3 2026 browser PDF benchmark methodology, 21 core workflow assertions, seven risk fixtures, three browser classes, and samples.",
    lede: "A public record of what the core release gate actually checks, what passed, and what still requires human review.",
    facts: [["Core workflows", "21"], ["Risk scenarios", "7"], ["Browser classes", "3"], ["Latest full gate", "Passed"]],
    sections: [
      { heading: "Methodology", body: "Each core workflow is mapped to at least one browser regression assertion. The full gate covers simple, complex-layout, scanned, encrypted, malformed, large-document, and mobile scenarios on desktop Chromium, Android Chromium, and iPhone WebKit classes.", bullets: ["Outputs are downloaded and reopened where the workflow produces a file.", "Assertions check concrete properties such as page count, file signatures, OOXML parts, extracted phrases, encryption structures, or reviewable comparison changes.", "Malformed and image-only recovery paths must leave the tool usable and explain the next safe action."] },
      { heading: "How to interpret the result", body: "A passed assertion means the named property was verified for the published fixture. It does not promise pixel-perfect reconstruction for every font, form, scan, spreadsheet, or presentation. The per-tool pages state the exact property measured." },
      { heading: "Performance collection", body: "PDFEnrich records privacy-safe operation duration, broad browser family, and device class when a user starts a supported export. Operations over 30 seconds are flagged for owner review. No filename, document text, or file content is included. Public percentiles will be added only after a statistically useful production sample exists." },
      { heading: "Reproduce or challenge it", body: "Download the fixtures below, run them through the named tool, and compare the output against the stated assertion. If you find a repeatable mismatch, include the browser family, device class, source fixture, expected property, and actual result in a support report." },
    ],
    downloads: [
      ["Simple searchable PDF", "/research/fixtures/simple-searchable.pdf", "2 pages · headings, paragraphs, and page numbering"],
      ["Complex layout PDF", "/research/fixtures/complex-layout.pdf", "2 pages · columns, table, vector shapes, and rotated label"],
      ["Clean scanned PDF", "/research/fixtures/scanned-clean.pdf", "1 image-only page · high contrast printed text"],
      ["Degraded scanned PDF", "/research/fixtures/scanned-degraded.pdf", "1 image-only page · skew, noise, and low contrast"],
      ["Encrypted PDF", "/research/fixtures/encrypted-sample.pdf", "Password: benchmark · authorized test fixture"],
      ["Malformed PDF", "/research/fixtures/malformed-sample.pdf", "Intentionally invalid · recovery testing only"],
      ["Large PDF", "/research/fixtures/large-100-pages.pdf", "100 pages · progressive loading and navigation"],
      ["Machine-readable result", "/research/benchmark/q3-2026-results.json", "Assertions, scope, date, and browser classes"],
    ],
    related: [
      toolLink("Browse the 21 core tools", ROUTE_PATHS.tools, "Open a released tool and see its exact measured assertion."),
      toolLink("OCR quality guide", ROUTE_PATHS.ocrQualityGuide, "Understand why scan quality changes recognition results."),
      toolLink("Report a reproducible problem", ROUTE_PATHS.support, "Send the fixture, expected property, and browser context."),
    ],
  },
  {
    ...common,
    id: "redact-pdf-safely",
    kind: "redaction",
    path: ROUTE_PATHS.redactGuide,
    eyebrow: "Illustrated redaction safety guide",
    title: "How to prove sensitive text is gone from a redacted PDF",
    seoTitle: "How to Redact a PDF Safely and Verify Hidden Text Is Removed | PDFEnrich",
    metaDescription: "Learn a proof-based PDF redaction workflow: remove source content, strip metadata, search and extract text, inspect pixels, and download safe test samples.",
    lede: "A black rectangle is not proof of redaction. The safe workflow removes the underlying content and then tests the exported file like a recipient would.",
    facts: [["Unsafe pattern", "Covering text with a shape"], ["PDFEnrich output", "Flattened rebuilt pages"], ["Required review", "Search, extraction, metadata, and pixels"]],
    sections: [
      { heading: "1. Mark only what must be removed", body: "Work from an authorized copy. Mark complete names, identifiers, signatures, barcodes, or surrounding context that could reconstruct the sensitive value. Keep an untouched source in a restricted location." },
      { heading: "2. Export a permanently rebuilt copy", body: "PDFEnrich's permanent redaction workflow rebuilds pages from rendered pixels, removes the original page content streams and metadata, and places the visible redaction marks into the new flattened pages. The result is no longer searchable, form-fillable, linked, layered, or tagged." },
      { heading: "3. Try to recover the secret", body: "Open the exported file, search for the value, drag-select around the redaction, copy and paste nearby content, inspect document properties, and run text extraction. For high-stakes disclosure, ask a second person to repeat the checks on a different PDF reader." },
      { heading: "4. Check visual leakage", body: "Zoom to at least 400 percent and inspect edges, partial characters, neighboring cells, headers, comments, attachments, and repeated values. Redaction is a document-review task, not just a drawing task." },
    ],
    downloads: [
      ["Unsafe before sample", "/research/redaction/redaction-before.pdf", "Contains a fictional account number as recoverable text"],
      ["Verified after sample", "/research/redaction/redaction-after.pdf", "Flattened page with the fictional value absent from text content"],
      ["Extraction proof", "/research/redaction/redaction-proof.txt", "Human-readable verification record for both sample files"],
    ],
    related: [
      toolLink("Permanently redact a PDF", ROUTE_PATHS.redactPdf, "Mark sensitive regions, rebuild the pages, and verify the output."),
      toolLink("Privacy", ROUTE_PATHS.privacy, "See what browser processing and analytics do and do not collect."),
      toolLink("Security reporting", ROUTE_PATHS.security, "Report a suspected exposure or product security issue."),
    ],
  },
  {
    ...common,
    id: "ocr-quality",
    kind: "ocr",
    path: ROUTE_PATHS.ocrQualityGuide,
    eyebrow: "Scanned PDF field guide",
    title: "Choose OCR settings by scan quality and document type",
    seoTitle: "Scanned PDF OCR Quality Guide by Scan and Document Type | PDFEnrich",
    metaDescription: "Improve OCR results with a practical matrix for clean scans, phone photos, forms, tables, receipts, multilingual print, faint copies, and handwriting.",
    lede: "OCR quality depends more on the source image and verification process than on a single accuracy percentage.",
    facts: [["Best input", "300 DPI, straight, high contrast"], ["Local languages", "English, Spanish, French, German, Italian, Portuguese"], ["Always review", "Names, dates, totals, and identifiers"]],
    sections: [
      { heading: "Start with the source", body: "Rescan at roughly 300 DPI when possible. Keep pages flat, fill the frame, use even light, remove shadows, and select the main document language. Cleanup can reduce noise but cannot recreate letters that were never captured." },
      { heading: "Use confidence as a review signal", body: "A high average confidence can still hide a wrong account number or name. Compare critical fields against the image, especially short strings, punctuation, decimal points, dates, and characters such as O/0 or I/1." },
      { heading: "Preserve the original", body: "Treat the searchable PDF and TXT as working derivatives. Keep the scan as the source of truth because OCR adds a machine-generated text layer and may misread layout or characters." },
    ],
    matrix: {
      caption: "Recommended OCR approach by source type",
      columns: ["Source", "Expected result", "Recommended setup", "Review focus"],
      rows: [
        ["Clean printed page", "Strong for normal fonts", "Auto cleanup, correct language, orientation on", "Names, dates, numbers"],
        ["Phone photo", "Variable around glare and perspective", "Retake square to page, even light, crop edges", "Shadow lines and curved text"],
        ["Form or table", "Words usually stronger than cell order", "High resolution, minimal cleanup", "Row/column association and checkboxes"],
        ["Receipt", "Variable for faded thermal print", "Increase contrast, keep full width", "Decimals, currency, totals, dates"],
        ["Faint photocopy", "Lower confidence", "Rescan darker before aggressive cleanup", "Dropped characters and broken words"],
        ["Multilingual print", "Best when the main language is selected", "Process separate language groups when possible", "Names and mixed-language lines"],
        ["Handwriting", "Unreliable in this workflow", "Manual transcription and second-person review", "Every field"],
      ],
    },
    downloads: [
      ["Clean scan fixture", "/research/fixtures/scanned-clean.pdf", "Use to confirm the basic OCR workflow"],
      ["Degraded scan fixture", "/research/fixtures/scanned-degraded.pdf", "Use to compare cleanup and orientation choices"],
    ],
    related: [
      toolLink("Run OCR on a PDF", ROUTE_PATHS.ocrPdf, "Create a searchable PDF and TXT file locally."),
      toolLink("Scan pages to PDF", "/scan-to-pdf", "Capture or combine page images before OCR."),
      toolLink("PDF to Word", ROUTE_PATHS.pdfToWord, "Convert searchable text after OCR is complete."),
    ],
  },
  {
    ...newGuideCommon,
    id: "how-to-edit-a-pdf",
    kind: "guide",
    path: ROUTE_PATHS.editPdfGuide,
    eyebrow: "Practical PDF editing guide",
    title: "How to edit a PDF online without breaking the original layout",
    seoTitle: "How to Edit a PDF Without Breaking the Layout | PDFEnrich",
    metaDescription: "Learn how to edit PDF text, add content, handle scanned pages, preserve untouched content, and verify the exported PDF before sharing it.",
    lede: "The safest edit is the smallest change that solves the problem. Identify whether the page contains native text or a scan, choose the right tool, and verify the exported copy like a recipient would.",
    facts: [["Best for", "Corrections, additions, markup, and page changes"], ["Scanned text", "Run OCR or add a new text box"], ["Final proof", "Reopen the export in a second reader"]],
    primaryAction: toolLink("Open Edit PDF", ROUTE_PATHS.editPdf, "Choose a PDF and make the change in your browser."),
    guideToolId: "edit-pdf",
    workedExample: {
      title: "A date correction with two missing initials",
      input: "A 12-page vendor agreement has one outdated date and two blank initials lines.",
      action: "Replace the supported date text, place two initials, and leave the other pages untouched.",
      result: "The regression export reopened successfully, retained the detected text style, and preserved untouched pages.",
      caption: "The editor regression checks detection, placement, history, export, and a parseable reopen.",
    },
    sections: [
      { heading: "1. Identify what kind of PDF you have", body: "Try selecting a word. Selectable text usually means the page contains native PDF text; an entire page that behaves like one image is probably scanned. Native text may support direct replacement. Scans need OCR for searchable text, or a carefully placed new text box when only a small visible correction is required.", bullets: ["Use Search to confirm whether important words exist as native text.", "Do not assume a visible word is editable just because it looks like normal text.", "Keep an untouched source copy before changing anything."] },
      { heading: "2. Choose the least invasive edit", body: "Replace supported detected text when the original font and layout can be approximated. Add a new text box for missing information. Use highlights, notes, shapes, or drawing when the goal is review rather than rewriting. Avoid flattening the whole document unless the workflow specifically requires it." },
      { heading: "3. Match the surrounding page", body: "Use a readable font size, align the baseline with nearby text, and leave enough room for longer replacement wording. Original embedded fonts are not always available in the browser, so line breaks and spacing may differ. Zoom in before export and check that the edit does not cover labels, borders, or adjacent content." },
      { heading: "4. Review document-wide effects", body: "Check the changed page at normal zoom, then inspect page order, rotation, links, forms, and representative untouched pages. If the PDF contains signatures, remember that changing the file may invalidate an existing cryptographic signature even when the visible signature remains." },
      { heading: "5. Export, reopen, and verify", body: "Download the edited copy and reopen it in a second PDF reader. Confirm that the file opens, the edit is visible at the intended coordinates, unchanged text is still selectable when expected, and the page count matches the source. Share only the reopened copy you actually checked." },
    ],
    related: [
      toolLink("Edit PDF", ROUTE_PATHS.editPdf, "Change supported text and add content in the full browser editor."),
      toolLink("OCR PDF", ROUTE_PATHS.ocrPdf, "Make image-only scanned text searchable before editing."),
      toolLink("Fill and sign a PDF guide", ROUTE_PATHS.fillAndSignPdfGuide, "Complete fields, place a signature, and verify the final copy."),
    ],
  },
  {
    ...newGuideCommon,
    id: "compress-pdf-without-losing-quality",
    kind: "guide",
    path: ROUTE_PATHS.compressPdfGuide,
    eyebrow: "PDF compression decision guide",
    title: "How to compress a PDF without losing the features you need",
    seoTitle: "How to Compress a PDF Without Losing Quality | PDFEnrich",
    metaDescription: "Choose the right PDF compression level, preserve text and forms, compare measured size savings, and verify image quality before sharing.",
    lede: "Compression is a tradeoff, not a magic percentage. Preserve the PDF structure first, use stronger image flattening only when necessary, and reject any attempted result that is larger or visibly unsuitable.",
    facts: [["Safest default", "Balanced structure-preserving cleanup"], ["Strongest reduction", "Flattened visual copy"], ["Success measure", "Smaller bytes and acceptable output"]],
    primaryAction: toolLink("Open Compress PDF", ROUTE_PATHS.compressPdf, "Measure a PDF and compare compression modes locally."),
    guideToolId: "compress-pdf",
    workedExample: {
      title: "An image-heavy PDF with an unoptimized page image",
      input: "The source fixture contains image data that can be reduced.",
      action: "Compress it at the selected quality level and compare the attempted output with the source.",
      result: "The tested output was smaller than the source and reopened as a valid PDF.",
      caption: "The compression regression compares actual byte size and reparses the downloaded result.",
    },
    sections: [
      { heading: "1. Decide what must survive compression", body: "If recipients need selectable text, working links, form fields, vector graphics, or accessibility structure, begin with Lossless cleanup or Balanced. If the document only needs to be viewed and the attachment limit is strict, Maximum reduction can create a smaller flattened visual copy at the cost of interactive features." },
      { heading: "2. Start with the structure-preserving modes", body: "Lossless cleanup focuses on compacting streams and unused objects. Balanced uses similar structure-preserving cleanup as the practical default. These modes do not intentionally turn every page into an image, so they are the right first attempt for reports, forms, contracts, and text-heavy documents." },
      { heading: "3. Use maximum reduction deliberately", body: "Maximum reduction renders pages to lower-quality JPEG images. It can help image-heavy scans, but it removes selectable text, links, fields, vectors, layers, and accessibility tags. Small text, diagrams, signatures, and fine lines deserve close visual review." },
      { heading: "4. Compare measured results", body: "Check the original and attempted byte sizes instead of trusting a generic quality label. A PDF that is already optimized may not become smaller. PDFEnrich keeps the original when the attempted result is larger and excludes that attempt from downloads." },
      { heading: "5. Verify before replacing the source", body: "Compare the first-page preview, reopen the complete output, and spot-check small text, images, page count, links, and forms that matter. Keep the source file. If a cryptographic signature is important, retain the signed original because compression changes file bytes and can invalidate signature verification." },
    ],
    related: [
      toolLink("Compress PDF", ROUTE_PATHS.compressPdf, "Measure before-and-after size and compare the visual result."),
      toolLink("Merge PDF", ROUTE_PATHS.mergePdf, "Combine the final source files before compressing the delivery copy."),
      toolLink("PDF benchmark", ROUTE_PATHS.pdfBenchmark, "Review the published regression method and test fixtures."),
    ],
  },
  {
    ...newGuideCommon,
    id: "how-to-combine-pdf-files",
    kind: "guide",
    path: ROUTE_PATHS.combinePdfGuide,
    eyebrow: "Ordered PDF packet guide",
    title: "How to combine PDF files in the right order without lowering quality",
    seoTitle: "How to Combine PDF Files in the Right Order | PDFEnrich",
    metaDescription: "Combine PDF files in a deliberate order, preserve native page quality, verify transition pages, and prepare one reliable PDF packet.",
    lede: "A useful merged PDF is more than several files joined together. Plan the reading order, remove accidental duplicates, preserve native pages, and inspect every transition between source documents.",
    facts: [["Native merge", "Pages are copied without rasterizing"], ["Current limit", "20 files and 200 total pages"], ["Critical review", "First, last, and transition pages"]],
    primaryAction: toolLink("Open Merge PDF", ROUTE_PATHS.mergePdf, "Arrange PDFs and create one ordered document."),
    guideToolId: "merge-pdf",
    workedExample: {
      title: "An application followed by its supporting letter",
      input: "A two-page application and a one-page supporting letter need to become one packet.",
      action: "Place the application first, the supporting letter second, and merge complete native pages.",
      result: "The regression output contained all three expected pages in the selected file order.",
      caption: "The merge regression reopens the download and counts the copied source pages.",
    },
    sections: [
      { heading: "1. Plan the packet before uploading", body: "Write the intended order in plain language: cover page, main document, attachments, exhibits, then optional reference material. Rename source files with simple sequence numbers when the order is easy to confuse. Remove drafts and duplicates before merging." },
      { heading: "2. Check every source PDF", body: "Open each file and confirm its page count, orientation, and authorization for inclusion. Password-protected PDFs must be unlocked only when you know the password and are allowed to modify them. Repair rotated or unwanted pages before the final merge." },
      { heading: "3. Arrange whole files in reading order", body: "Drag the source files into their final sequence. Each file keeps its own internal page order. If pages inside one source need rearranging, organize that PDF first and then return to the merge workflow." },
      { heading: "4. Preserve native pages when possible", body: "A native merge copies complete PDF pages instead of taking screenshots. This retains original page dimensions, selectable text, vector graphics, rotation, and embedded page content. Mixed page sizes are valid, but check how they look when scrolling or printing." },
      { heading: "5. Inspect every transition", body: "Confirm the final page count equals the total shown before merging. Open the first and last page, then check the boundary where each source file begins. Verify that attachments follow the document that references them and that no blank or duplicate page slipped into the packet." },
    ],
    related: [
      toolLink("Merge PDF", ROUTE_PATHS.mergePdf, "Combine up to 20 PDFs in your chosen order."),
      toolLink("Organize PDF", "/organize-pdf", "Reorder, rotate, duplicate, or remove pages before merging."),
      toolLink("Compress PDF guide", ROUTE_PATHS.compressPdfGuide, "Reduce the finished delivery copy only after its order is final."),
    ],
  },
  {
    ...newGuideCommon,
    id: "how-to-fill-and-sign-pdf",
    kind: "guide",
    path: ROUTE_PATHS.fillAndSignPdfGuide,
    eyebrow: "PDF form completion guide",
    title: "How to fill and sign a PDF correctly before you submit it",
    seoTitle: "How to Fill and Sign a PDF Correctly Online | PDFEnrich",
    metaDescription: "Fill PDF fields, add checks, dates, initials, and a signature, distinguish visual signing from digital certificates, and verify the final copy.",
    lede: "Complete the document before signing it. Use interactive fields when they exist, place answers carefully on flat forms when they do not, and treat the reopened downloaded PDF as the submission copy.",
    facts: [["Field types", "Interactive fields or placed answers"], ["Signature", "Typed, drawn, or uploaded visual mark"], ["Not included", "Certificate-based identity verification"]],
    primaryAction: toolLink("Open Fill PDF", "/fill-pdf", "Complete a flat PDF with text, checks, dates, initials, and signatures."),
    guideToolId: "sign-pdf",
    workedExample: {
      title: "A one-page approval form with a typed signature",
      input: "The form needs a visible signature on one specific signature line.",
      action: "Create the typed signature, place it at the selected coordinates, and export the completed page.",
      result: "The expected signature text remained present after the PDF was downloaded and reopened.",
      caption: "The signing regression places a signature, exports the PDF, and inspects the reopened content.",
    },
    sections: [
      { heading: "1. Complete every required answer first", body: "Read the entire form before signing. Add text, checks, dates, and initials while the content can still be reviewed. A signature should confirm the finished document, not a version with unanswered fields or unclear attachments." },
      { heading: "2. Use interactive fields when available", body: "Supported AcroForm fields can hold text, checkboxes, radio choices, dropdowns, and list selections. A flat form has no interactive widgets, so answers must be placed visually over the correct lines or boxes. Do not cover field labels or instructions." },
      { heading: "3. Create the right visual signature", body: "Type a name for a keyboard-accessible signature, draw with a pointer or touchscreen, or upload a closely cropped image. A transparent PNG usually produces the cleanest uploaded result. Resize the mark to fit the line without obscuring nearby text." },
      { heading: "4. Understand what the signature proves", body: "PDFEnrich self-signing places a visual self-attested signature and flattens it into the exported PDF. It does not issue a cryptographic certificate, verify government identity, provide notarization, or guarantee legal acceptance. Use an approved signature service when a recipient requires those controls." },
      { heading: "5. Reopen the exact submission copy", body: "Download and reopen the finished PDF. Check every required field, signature, initial, date, attachment, and page. Confirm the page count and filename, then submit the same verified download rather than an earlier draft." },
    ],
    related: [
      toolLink("Fill PDF", "/fill-pdf", "Place answers on flat or non-interactive PDF pages."),
      toolLink("Sign PDF", ROUTE_PATHS.signPdf, "Type, draw, or upload a visual self-signature."),
      toolLink("PDF Form Filler", "/pdf-form-filler", "Complete supported interactive AcroForm fields."),
    ],
  },
  {
    ...newGuideCommon,
    id: "pdf-to-word-formatting",
    kind: "guide",
    path: ROUTE_PATHS.pdfToWordGuide,
    eyebrow: "PDF to Word formatting guide",
    title: "How to convert PDF to Word and choose the right layout mode",
    seoTitle: "PDF to Word Formatting and Layout Guide | PDFEnrich",
    metaDescription: "Choose editable, scanned OCR, or visual-fidelity PDF to Word conversion and learn what to check in headings, columns, tables, fonts, and page breaks.",
    lede: "PDF describes where page elements sit; Word describes how a document flows. Choose editable reconstruction for reusable text, OCR for image-only pages, or visual fidelity when appearance matters more than editing.",
    facts: [["Editable mode", "Reconstructed DOCX paragraphs"], ["Scanned mode", "Local OCR in six languages"], ["Visual mode", "Page images inside DOCX"]],
    primaryAction: toolLink("Open PDF to Word", ROUTE_PATHS.pdfToWord, "Choose editable, scanned OCR, or visual-fidelity conversion."),
    guideToolId: "pdf-to-word",
    workedExample: {
      title: "A text report with headings and a fixed page break",
      input: "The source PDF contains positioned headings, paragraphs, and a known page boundary.",
      action: "Create editable DOCX paragraph structure and retain a visual-fidelity fallback.",
      result: "The regression DOCX contained a valid Word document body and a working visual fallback.",
      caption: "The conversion regression inspects the OOXML package and the image-only recovery path.",
    },
    sections: [
      { heading: "1. Choose the output based on your next task", body: "Use Editable when you need to revise wording, copy paragraphs, or reuse headings. Use Scanned PDF — editable OCR when the pages are images. Use Visual fidelity when the document mainly needs to look like the source inside Word and full text editing is less important." },
      { heading: "2. Know what editable reconstruction can preserve", body: "Editable conversion can retain extracted text order, page breaks, indentation, spacing, common font styling, and tab-aligned columns. It cannot recover the original authoring structure perfectly because PDF text may be stored as individually positioned fragments rather than paragraphs, tables, or flowing columns." },
      { heading: "3. Treat tables and columns as review zones", body: "Check row-to-column relationships, wrapped cells, multi-column reading order, floating text boxes, headers, footers, and footnotes. A visually correct PDF can still have ambiguous extraction order. Rebuild critical tables in Word when their structure matters more than a quick approximation." },
      { heading: "4. Use OCR only for image-only pages", body: "Select the document’s main language and compare recovered names, dates, totals, and identifiers against the visible scan. OCR creates machine-recognized text and can misread low-resolution characters, handwriting, shadows, or mixed languages. Keep the scan as the source of truth." },
      { heading: "5. Verify the DOCX in a real editor", body: "Open the result in Word, LibreOffice, or another DOCX editor. Compare page count, headings, lists, paragraph order, fonts, columns, tables, images, and page breaks. Save the corrected DOCX as the editable master and retain the source PDF for visual reference." },
    ],
    related: [
      toolLink("PDF to Word", ROUTE_PATHS.pdfToWord, "Convert with editable, OCR, or visual-fidelity output."),
      toolLink("OCR PDF", ROUTE_PATHS.ocrPdf, "Create searchable text from scans before other workflows."),
      toolLink("Word to PDF", "/word-to-pdf", "Export the reviewed DOCX back to a fixed searchable PDF."),
    ],
  },
  ...SEARCH_GUIDES,
  PDF_ATTACHMENT_SIZE_STUDY,
  {
    ...common,
    id: "education-workflow",
    kind: "workflow",
    path: ROUTE_PATHS.educationWorkflow,
    eyebrow: "Workflow playbook for educators",
    title: "Move forms, handouts, and approvals through one reviewable PDF workflow",
    seoTitle: "PDF Workflow Guide for Educators and School Operations | PDFEnrich",
    metaDescription: "A practical educator PDF workflow for scanning forms, making text searchable, combining packets, redacting student data, collecting signatures, and archiving.",
    lede: "A repeatable path for turning mixed paper and digital documents into an accessible, reviewable packet without losing the source of truth.",
    facts: [["Typical inputs", "Scans, DOCX, slides, forms"], ["Primary risk", "Student data and unreadable scans"], ["Final check", "Page order, accessibility, and authorization"]],
    sections: [
      { heading: "Intake and naming", body: "Create one restricted source folder, name files with course or case identifiers that do not expose unnecessary personal data, and record who is authorized to view the packet." },
      { heading: "Prepare the packet", body: "Run OCR on image-only forms, convert approved Word or slide content to PDF, merge materials in reading order, and add page numbers after the order is final.", bullets: ["Keep original scans beside the OCR derivative.", "Use descriptive filenames instead of student names when possible.", "Check charts, math notation, and tables after conversion."] },
      { heading: "Review and release", body: "Permanently redact information the recipient should not receive, verify redaction, add signatures or initials only after content approval, and reopen the final PDF in a second reader." },
      { heading: "Archive and migrate", body: "Store the editable source, signed final PDF, and approval record separately. When moving from email attachments to a shared workspace, migrate approved finals first and keep a documented owner for retention and deletion." },
    ],
    related: [toolLink("OCR PDF", ROUTE_PATHS.ocrPdf, "Make scanned forms searchable."), toolLink("Merge PDF", ROUTE_PATHS.mergePdf, "Combine the complete packet in order."), toolLink("Redaction guide", ROUTE_PATHS.redactGuide, "Remove student data and prove it is absent.")],
  },
  {
    ...common,
    id: "recruiting-workflow",
    kind: "workflow",
    path: ROUTE_PATHS.recruitingWorkflow,
    eyebrow: "Workflow playbook for recruiting",
    title: "Create consistent candidate packets without leaking private notes",
    seoTitle: "PDF Workflow Guide for Recruiters and Hiring Teams | PDFEnrich",
    metaDescription: "A recruiter PDF workflow for resumes, scorecards, offer letters, signatures, redaction, candidate packets, retention, and migration from email attachments.",
    lede: "Separate candidate-facing documents from internal evaluation evidence, then make every handoff deliberate and reviewable.",
    facts: [["Typical inputs", "Resumes, scorecards, offer DOCX"], ["Primary risk", "Internal notes in candidate copies"], ["Final check", "Correct candidate, version, and recipients"]],
    sections: [
      { heading: "Separate working and candidate-facing files", body: "Keep interview notes and evaluation scorecards in a restricted location. Build the candidate-facing packet only from approved documents, never by forwarding a working folder." },
      { heading: "Standardize review", body: "Use the editable evaluation scorecard, capture evidence rather than protected characteristics, convert approved materials to PDF, and compare offer revisions before signature." },
      { heading: "Sign and verify", body: "Confirm compensation, title, manager, location, dates, and contingencies against the approved source. Self-sign only where appropriate; a visual signature is not certificate-based identity verification." },
      { heading: "Retention and migration", body: "Define a retention owner and deletion schedule before moving from personal inboxes into a shared recruiting system. Migrate final records with consistent candidate IDs and remove duplicate local copies when policy permits." },
    ],
    related: [toolLink("Compare PDFs", "/compare-pdf", "Review offer and policy revisions."), toolLink("Protect PDF", "/protect-pdf", "Add an open password when authorized and appropriate.")],
  },
  {
    ...common,
    id: "legal-operations-workflow",
    kind: "workflow",
    path: ROUTE_PATHS.legalOperationsWorkflow,
    eyebrow: "Workflow playbook for legal operations",
    title: "Control versions, compare changes, redact evidence, and release the right PDF",
    seoTitle: "PDF Workflow Guide for Legal Operations and Contract Review | PDFEnrich",
    metaDescription: "A legal operations PDF workflow for version control, contract comparison, permanent redaction, signature boundaries, production checks, retention, and migration.",
    lede: "PDF tools can support document operations, but they do not replace legal review, e-discovery systems, certificate signatures, or a defensible retention program.",
    facts: [["Typical inputs", "Contracts, exhibits, productions"], ["Primary risk", "Wrong version or incomplete redaction"], ["Final check", "Second-person review and matter record"]],
    sections: [
      { heading: "Establish the source and authority", body: "Identify the matter, document owner, authoritative editable source, and permitted recipients. Preserve originals and avoid editing the only copy." },
      { heading: "Compare revisions", body: "Compare final PDF versions for additions, deletions, replacements, and moved text. Treat detections as review prompts and confirm every material change against both source documents." },
      { heading: "Redact and validate", body: "Use permanent redaction, then search, select, extract text, inspect metadata, and review visible edges. High-stakes productions require a second reviewer and any additional controls required by counsel or policy." },
      { heading: "Release and retain", body: "Record the approved version, recipients, release date, and reviewer. PDFEnrich does not provide a legal hold, audit certificate, signing ceremony, or e-discovery chain of custody." },
    ],
    related: [toolLink("Compare two PDFs", "/compare-pdf", "Review text and focused visual changes."), toolLink("Safe redaction guide", ROUTE_PATHS.redactGuide, "Prove hidden text was removed."), toolLink("Security architecture", ROUTE_PATHS.architecture, "Understand where processing and optional storage occur.")],
  },
  {
    ...common,
    id: "real-estate-workflow",
    kind: "workflow",
    path: ROUTE_PATHS.realEstateWorkflow,
    eyebrow: "Workflow playbook for real estate",
    title: "Assemble property packets that are complete, legible, and ready for review",
    seoTitle: "PDF Workflow Guide for Real Estate Documents and Property Packets | PDFEnrich",
    metaDescription: "A real estate PDF workflow for inspection photos, disclosures, offers, leases, signatures, redaction, comparison, page order, and final packet verification.",
    lede: "Keep property evidence, editable drafts, signed documents, and distribution copies distinct so the right version reaches the right person.",
    facts: [["Typical inputs", "Photos, inspections, disclosures, offers"], ["Primary risk", "Missing pages or outdated terms"], ["Final check", "Property, parties, dates, initials, attachments"]],
    sections: [
      { heading: "Prepare source material", body: "Label property photos, complete the inspection checklist, scan paper disclosures square to the page, and run OCR when searchable text will help review." },
      { heading: "Assemble in reading order", body: "Convert approved source documents, merge the main agreement and exhibits, add page numbers after final ordering, and compress only a distribution copy when upload limits require it." },
      { heading: "Compare and sign", body: "Compare revised offers or leases, confirm every changed amount and date, then place authorized signatures and initials precisely. A visual self-signature does not provide identity verification or an audit certificate." },
      { heading: "Deliver and archive", body: "Reopen the full packet, check property address and parties on every relevant document, confirm required exhibits, and retain the authoritative source and signed final according to your policy." },
    ],
    related: [toolLink("Merge PDF", ROUTE_PATHS.mergePdf, "Build the final property packet."), toolLink("Compare PDFs", "/compare-pdf", "Review changed terms before signing.")],
  },
  {
    ...common,
    id: "small-business-workflow",
    kind: "workflow",
    path: ROUTE_PATHS.smallBusinessWorkflow,
    eyebrow: "Workflow playbook for small businesses",
    title: "Turn everyday documents into a controlled client-ready PDF process",
    seoTitle: "PDF Workflow Guide for Small Businesses and Client Documents | PDFEnrich",
    metaDescription: "A small-business PDF workflow for invoices, proposals, receipts, contracts, signatures, client packets, password protection, retention, and cloud migration.",
    lede: "A lightweight process can still separate drafts from approved records, reduce attachment mistakes, and make client delivery easier to verify.",
    facts: [["Typical inputs", "Invoices, proposals, receipts, contracts"], ["Primary risk", "Sending drafts or exposing client data"], ["Final check", "Client, amount, due date, attachments, access"]],
    sections: [
      { heading: "Standardize editable sources", body: "Start from a controlled invoice, proposal, or agreement template. Replace all prompts, validate customer details and totals, and keep the DOCX or spreadsheet as the editable master." },
      { heading: "Create the delivery copy", body: "Convert approved sources to PDF, merge supporting material, add page numbers when useful, and use compression only when it produces a smaller acceptable copy." },
      { heading: "Protect only when it helps", body: "Use a strong open password for authorized confidential attachments and send the password through a separate channel. Password protection does not prevent screenshots or misuse after opening." },
      { heading: "Migrate out of personal inboxes", body: "Move approved masters and final PDFs into a shared system with named owners, access rules, backups, and a retention schedule. Do not treat email threads as the only document record." },
    ],
    related: [toolLink("Word to PDF", "/word-to-pdf", "Create a searchable client-ready PDF."), toolLink("Protect PDF", "/protect-pdf", "Add an AES-256 open password locally.")],
  },
  {
    ...common,
    id: "privacy",
    kind: "trust",
    path: ROUTE_PATHS.privacy,
    eyebrow: "Trust center",
    title: "Privacy boundaries you can understand before choosing a file",
    seoTitle: "Privacy Policy and Browser PDF Processing | PDFEnrich",
    metaDescription: "See how PDFEnrich handles browser-only PDF processing, optional Firebase accounts and cloud history, local storage, analytics, support requests, and deletion.",
    lede: "Supported core tools process document contents in your browser. Optional account, cloud-history, analytics, and support features have separate, clearly stated data paths.",
    facts: [["Document analytics", "No filenames, text, signatures, or contents"], ["Guest core tools", "No account required"], ["Policy effective", "July 20, 2026"]],
    sections: [
      { heading: "Browser processing", body: "The editor and supported PDF tools process file contents in the current browser tab. Choosing a file does not send its bytes to PDFEnrich merely to run those tools." },
      { heading: "Optional account and cloud features", body: "Firebase Authentication handles sign-in. PDFEnrich stores an owner-only account directory with the account name, email, sign-in method, and Firebase last-sign-in time so the operator can review account access. When Firebase Storage and Firestore are configured, signed-in users may also save document history and workspace data for cross-device access. Guest processing does not require cloud history." },
      { heading: "Local storage", body: "Guest and signed-in work may be saved in browser storage when space allows. You, the browser, private-browsing rules, or device cleanup can remove it." },
      { heading: "Product analytics", body: "Privacy-safe events can include route, traffic-source category, referring hostname, tool, broad file-size and page-count buckets, validation category, duration, browser family, device class, and success or failure. They exclude search terms, full referring URLs, filenames, file contents, extracted text, document URLs, signatures, form values, and user-entered document data." },
      { heading: "Support and service providers", body: "Support requests store the reply email, category, message, account ID when signed in, and submission time in the owner-only inbox. Vercel currently hosts the public application and Google Firebase provides optional authentication, Firestore, and Storage." },
      { heading: "Deletion", body: "Clear site data to remove guest browser records. Signed-in users can delete saved documents or permanently delete their account and associated document records, cloud payloads, sign-in directory profile, linked analytics events, and account-linked support requests from Settings. Anonymous events cannot always be linked back to a person." },
    ],
    related: [toolLink("Data retention", ROUTE_PATHS.dataRetention, "See storage lifecycles and deletion boundaries."), toolLink("Architecture", ROUTE_PATHS.architecture, "Follow each data path through the product."), toolLink("Contact support", ROUTE_PATHS.support, "Request privacy or deletion help.")],
  },
  {
    ...common,
    id: "security",
    kind: "trust",
    path: ROUTE_PATHS.security,
    eyebrow: "Trust center",
    title: "Current security controls, product boundaries, and reporting path",
    seoTitle: "Security Controls and Vulnerability Reporting | PDFEnrich",
    metaDescription: "Review PDFEnrich browser-processing boundaries, authentication and owner access, PDF password handling, dependencies, current limitations, and security reporting.",
    lede: "Security documentation should distinguish implemented controls from aspirations. This page does not claim an external audit, certification, or compliance program that has not been completed.",
    facts: [["Core processing", "Current browser tab"], ["Owner analytics", "Restricted to the configured owner account"], ["External certification", "None claimed"]],
    sections: [
      { heading: "Browser boundary", body: "Supported core PDF work runs locally, reducing document transfer. Browser-only processing is not the same as end-to-end encryption, a sandbox guarantee, or a formal compliance certification." },
      { heading: "Identity and access", body: "Firebase Authentication supports email and Google sign-in. Private app routes require authentication, document records are scoped to their owner, and the analytics dashboard checks the configured owner identity." },
      { heading: "Passwords and sensitive values", body: "PDF passwords are used in browser memory for the requested operation and are not included in product analytics. PDFEnrich cannot recover a password it does not store." },
      { heading: "Dependencies and releases", body: "The product uses pinned application dependencies, automated unit and browser regression suites, route audits, and a core quality gate before release. This reduces risk but cannot prove the absence of vulnerabilities." },
      { heading: "Report a security issue", body: "Use Support and choose Security. Include the affected route, impact, reproduction steps, and a safe test file if needed. Do not send real credentials, secrets, or another person's confidential PDF." },
    ],
    related: [toolLink("Architecture", ROUTE_PATHS.architecture, "See processing, storage, identity, and analytics boundaries."), toolLink("Incident history", ROUTE_PATHS.incidentHistory, "Review the public incident-log policy and entries."), toolLink("Support", ROUTE_PATHS.support, "Report a product security concern.")],
  },
  {
    ...common,
    id: "architecture",
    kind: "architecture",
    path: ROUTE_PATHS.architecture,
    eyebrow: "Trust center",
    title: "How PDFEnrich processes documents, identity, storage, and analytics",
    seoTitle: "Product Architecture and Data Flow | PDFEnrich",
    metaDescription: "Understand PDFEnrich's browser PDF engine, optional Firebase authentication and cloud history, privacy-safe analytics, Vercel delivery, and trust boundaries.",
    lede: "Four separate paths explain most of the product: static app delivery, local document processing, optional signed-in storage, and privacy-safe operational events.",
    facts: [["PDF engine", "Runs in the browser"], ["Identity", "Firebase Authentication"], ["Optional cloud history", "Firestore and Firebase Storage"], ["App delivery", "Vercel"]],
    sections: [
      { heading: "1. Application delivery", body: "The public React application and static assets are delivered to the browser. Editor and conversion code is loaded only when a route needs it so the marketing and resource pages do not preload the PDF engine." },
      { heading: "2. Local document processing", body: "Supported tools read the chosen file into browser memory, perform the operation on-device, and create a local download. Closing the tab releases memory; browser-saved work follows local storage rules." },
      { heading: "3. Optional identity and cloud history", body: "Firebase Authentication handles sign-in. Signed-in document history can use Firestore for records and Firebase Storage for payloads when configured. Guest use does not depend on this path." },
      { heading: "4. Operational analytics and support", body: "Bounded events record route, tool, broad file characteristics, outcome, duration, and broad client class without document content. Support messages are separate records readable only by the site owner." },
      { heading: "Trust boundaries", body: "Your device and browser remain part of the security model. External services have their own operational boundaries. PDFEnrich has not completed a SOC 2 audit, ISO certification, penetration-test publication, or enterprise SLA." },
    ],
    related: [toolLink("Privacy", ROUTE_PATHS.privacy, "Read the data categories and deletion choices."), toolLink("Security", ROUTE_PATHS.security, "Review controls, limitations, and reporting."), toolLink("Data retention", ROUTE_PATHS.dataRetention, "Understand storage lifecycles.")],
  },
  {
    ...common,
    id: "uptime",
    kind: "trust",
    path: ROUTE_PATHS.uptime,
    eyebrow: "Trust center",
    title: "Service availability and current monitoring commitments",
    seoTitle: "Service Uptime and Availability | PDFEnrich",
    metaDescription: "See PDFEnrich's current service availability model, browser and third-party dependencies, monitoring scope, known limitations, and future public uptime reporting plan.",
    lede: "PDFEnrich is currently a free public-beta service with no paid SLA. Core processing can continue locally after the app loads, while sign-in and cloud history depend on external services.",
    facts: [["Paid SLA", "Not offered"], ["Published historical percentage", "Not enough verified data yet"], ["Incident log start", "July 21, 2026"]],
    sections: [
      { heading: "What availability means", body: "The public app must load for a user to start. After a supported tool is loaded, the PDF operation runs in the browser. Sign-in and cloud history separately depend on Firebase, and public delivery depends on the hosting provider and the user's network." },
      { heading: "Current monitoring", body: "Release checks cover route availability, prerendered HTML, public metadata, core workflows, and browser/device classes. Owner analytics records bounded failures and slow operations. A third-party public uptime monitor and historical percentage are not yet established." },
      { heading: "No invented percentage", body: "PDFEnrich will not display 99.9 percent or another availability figure until a defined external monitor has collected enough continuous data. When reporting begins, this page will publish the monitor, regions, interval, exclusions, and calculation window." },
      { heading: "If a tool appears unavailable", body: "Reload once, confirm the file meets the stated limits, try the published benchmark fixture, and report the route, browser family, device class, approximate time, and visible error through Support." },
    ],
    related: [toolLink("Incident history", ROUTE_PATHS.incidentHistory, "See the log policy and public entries."), toolLink("Quarterly benchmark", ROUTE_PATHS.pdfBenchmark, "Review release assertions separately from service uptime."), toolLink("Support", ROUTE_PATHS.support, "Report an availability problem.")],
  },
  {
    ...common,
    id: "incident-history",
    kind: "incidents",
    path: ROUTE_PATHS.incidentHistory,
    eyebrow: "Trust center",
    title: "Public incident history and disclosure policy",
    seoTitle: "Public Incident History | PDFEnrich",
    metaDescription: "Review PDFEnrich's incident disclosure policy, log start date, severity thresholds, update expectations, current entries, and security or availability reporting path.",
    lede: "The public log begins July 21, 2026. Earlier absence of entries is not presented as proof that no issue ever occurred.",
    facts: [["Log begins", "July 21, 2026"], ["Current public entries", "0"], ["Status", "No published incident since log start"]],
    sections: [
      { heading: "Current log", body: "No security or availability incident meeting the publication threshold has been entered since this public log began on July 21, 2026." },
      { heading: "What will be published", body: "A material incident entry will state the affected feature, user-visible impact, start and resolution times when known, containment, recovery, and follow-up actions. Sensitive exploit detail may be delayed until users are protected." },
      { heading: "Severity threshold", body: "Publication covers confirmed unauthorized access to customer data, material loss or corruption of stored account data, or sustained production unavailability with broad user impact. Individual malformed-file errors remain support and quality issues unless they reveal a broader incident." },
      { heading: "Corrections", body: "Entries may be updated as facts improve. Material corrections will retain the original publication date and clearly state what changed." },
      { heading: "Report an issue", body: "Use Support and choose Security or Product problem. Include safe reproduction information and do not send passwords, production secrets, or unrelated confidential files." },
    ],
    related: [toolLink("Security", ROUTE_PATHS.security, "Review controls and vulnerability reporting."), toolLink("Uptime", ROUTE_PATHS.uptime, "Understand availability commitments and monitoring gaps."), toolLink("Support", ROUTE_PATHS.support, "Submit a security or availability report.")],
  },
]);

export const EDITORIAL_RESOURCE_BY_PATH = new Map(EDITORIAL_RESOURCE_PAGES.map((page) => [page.path, page]));
