import { ROUTE_PATHS } from "../router/routePaths.js";
import { PRODUCT_RESPONSIBLE_PARTY } from "./toolEvidence.js";

const published = {
  publishedIso: "2026-07-29",
  reviewedIso: "2026-07-29",
  reviewedLabel: "July 29, 2026",
  owner: PRODUCT_RESPONSIBLE_PARTY,
};

/** @param {string} label @param {string} path @param {string} description */
const toolLink = (label, path, description) => ({ label, path, description });

export const SEARCH_GUIDES = Object.freeze([
  {
    ...published,
    id: "edit-pdf-on-iphone",
    kind: "search-guide",
    path: ROUTE_PATHS.editPdfOnIphoneGuide,
    eyebrow: "iPhone PDF editing guide",
    title: "How to edit a PDF on iPhone without installing another app",
    seoTitle: "How to Edit a PDF on iPhone Online | PDFEnrich",
    metaDescription: "Edit a PDF on iPhone in Safari, add text or a signature, handle scanned pages, avoid tiny controls, and verify the downloaded PDF before sharing.",
    lede: "Safari can handle a focused PDF edit without moving the document through another mobile app. Start with one small change, use touch-friendly controls, and verify the saved copy from Files.",
    facts: [["Works in", "Safari on iPhone"], ["Good for", "Text, signatures, markup, and pages"], ["File path", "Files app to Safari and back"]],
    primaryAction: toolLink("Edit a PDF on iPhone", ROUTE_PATHS.editPdf, "Choose a PDF from Files and open the touch editor."),
    guideToolId: "edit-pdf",
    workedExample: {
      title: "Correct one date from an iPhone",
      input: "A PDF in the Files app contains one outdated date on page two.",
      action: "Open it in Safari, zoom to the line, replace or cover the old date, and add the corrected date.",
      result: "The saved copy should reopen from Downloads with the correction aligned and every other page present.",
      caption: "PDFEnrich uses a touch-first editor dock and browser download flow on phones.",
    },
    sections: [
      { heading: "1. Open the PDF from Files", body: "In Safari, open PDFEnrich and choose the document from On My iPhone, iCloud Drive, or another Files provider. The supported editor reads the selected file in the browser. Keep the original in Files so the edited download remains a separate copy." },
      { heading: "2. Make one precise change at a time", body: "Pinch to zoom before placing text, initials, highlights, or a signature. Use the six-action dock for frequent tools and More for the remaining editor controls. Touch handles are easier to control when the page is zoomed in and the document is not moving underneath your finger." },
      { heading: "3. Treat scanned pages differently", body: "If an entire page behaves like a photograph, its visible words are not normal editable text. Run OCR when searchable text matters, or place a new text box over the correct location for a small visual correction. Never assume a scan became structurally editable just because text is visible." },
      { heading: "4. Download and verify in Files", body: "Download the edited PDF, open it from the Safari downloads button or Files, and check the changed page at normal zoom. Confirm page count, orientation, signatures, and any form answers before attaching the downloaded copy to a message." },
    ],
    related: [
      toolLink("Edit PDF", ROUTE_PATHS.editPdf, "Open the full touch-friendly PDF editor."),
      toolLink("Edit a scanned PDF", ROUTE_PATHS.editScannedPdfGuide, "Choose between OCR and a visual correction."),
      toolLink("Sign a PDF on Android", ROUTE_PATHS.signPdfOnAndroidGuide, "Follow the equivalent mobile signing workflow."),
    ],
  },
  {
    ...published,
    id: "edit-scanned-pdf",
    kind: "search-guide",
    path: ROUTE_PATHS.editScannedPdfGuide,
    eyebrow: "Scanned PDF editing guide",
    title: "How to edit a scanned PDF when the page is really an image",
    seoTitle: "How to Edit a Scanned PDF with OCR | PDFEnrich",
    metaDescription: "Learn when a scanned PDF needs OCR, when a placed text correction is enough, how to avoid hiding evidence, and how to verify the final searchable copy.",
    lede: "A scanned PDF stores page photographs, not ordinary paragraphs. Decide whether you need searchable text, a small visible correction, or a complete reconstruction before changing it.",
    facts: [["First test", "Try selecting one word"], ["Searchable result", "Run OCR first"], ["Small correction", "Place a matched text box"]],
    primaryAction: toolLink("Run OCR on the scan", ROUTE_PATHS.ocrPdf, "Create a searchable copy before editing extracted content."),
    guideToolId: "ocr-pdf",
    workedExample: {
      title: "Make a two-page phone scan searchable",
      input: "A phone-scanned form contains clear printed English text but no selectable words.",
      action: "Run OCR with the correct language, download the searchable PDF, and search for a known reference value.",
      result: "A successful check finds the reference text while keeping both original page images visible.",
      caption: "The OCR workflow keeps the page image and adds a searchable text layer.",
    },
    sections: [
      { heading: "1. Confirm that the page is image-only", body: "Open the PDF and try to select a single word or search for a phrase that is clearly visible. If the whole page selects as one object or Search finds nothing, the page is probably an image. Mixed PDFs can contain both searchable and scanned pages." },
      { heading: "2. Choose OCR or a visual correction", body: "Run OCR when recipients need to search, copy, or convert the text. For one small visible correction, a new text box may be faster, but it does not change the words inside the underlying image. Keep the unmodified scan whenever document history or evidence matters." },
      { heading: "3. Improve the source before OCR", body: "Straighten rotated pages, crop empty borders, and use an evenly lit scan with readable contrast. Select the main document language. Glare, folds, handwriting, stamps, faint carbon copies, and multi-column forms need more manual review than clean printed pages." },
      { heading: "4. Verify names, dates, and numbers", body: "Search the OCR result for a known phrase, then compare important names, dates, totals, decimal points, and identifiers against the scan. OCR confidence is not proof of accuracy. Reopen the exported PDF and confirm the text layer aligns with the visible page." },
    ],
    related: [
      toolLink("OCR PDF", ROUTE_PATHS.ocrPdf, "Make scanned pages searchable in the browser."),
      toolLink("OCR quality guide", ROUTE_PATHS.ocrQualityGuide, "Choose settings by scan and document type."),
      toolLink("Edit PDF", ROUTE_PATHS.editPdf, "Add a careful visible correction after reviewing the scan."),
    ],
  },
  {
    ...published,
    id: "compress-pdf-to-1mb",
    kind: "search-guide",
    path: ROUTE_PATHS.compressPdfToOneMbGuide,
    eyebrow: "One-megabyte PDF guide",
    title: "How to compress a PDF to 1 MB without pretending every file can fit",
    seoTitle: "Compress a PDF to 1 MB Online | PDFEnrich",
    metaDescription: "Reduce a PDF toward a 1 MB upload limit, compare measured file sizes, preserve searchable structure when possible, and know when splitting is safer.",
    lede: "A 1 MB target is a hard byte budget, not a quality setting. Measure the starting file, preserve structure first, and split the document when acceptable quality cannot fit the limit.",
    facts: [["Target", "1 MiB = 1,048,576 bytes"], ["Safest first pass", "Balanced compression"], ["Fallback", "Split or flatten a delivery copy"]],
    primaryAction: toolLink("Compress toward 1 MB", ROUTE_PATHS.compressPdf, "Compare measured modes and keep only a smaller valid result."),
    guideToolId: "compress-pdf",
    workedExample: {
      title: "Reduce an image-heavy application packet",
      input: "A multi-page application must fit a portal that rejects files over 1 MB.",
      action: "Try structure-preserving compression, inspect the measured result, then use stronger reduction only on a separate delivery copy.",
      result: "The correct outcome is either a verified PDF below the portal limit or an honest decision to split the packet.",
      caption: "PDFEnrich reports actual before-and-after bytes instead of promising a fixed percentage.",
    },
    sections: [
      { heading: "1. Confirm what the portal means by 1 MB", body: "Some systems use 1,000,000 bytes and others use 1 MiB, or 1,048,576 bytes. Aim slightly below the displayed limit because upload systems may apply their own message or metadata overhead. Record the original size before changing anything." },
      { heading: "2. Preserve document structure first", body: "Use Lossless cleanup or Balanced when selectable text, links, form fields, vectors, or accessibility structure matter. These modes may produce modest savings on text-heavy or already optimized PDFs, but they avoid turning every page into a photograph." },
      { heading: "3. Use stronger reduction only when appropriate", body: "Maximum reduction can help image-heavy scans by rendering lower-quality page images. It removes interactive and searchable structure and can soften small text, signatures, diagrams, and fine lines. Always apply it to a copy and inspect representative pages." },
      { heading: "4. Split instead of destroying readability", body: "If the result remains above 1 MB at acceptable quality, split the document into clearly named parts when the recipient allows multiple uploads. Reopen every output, check page count and order, and never replace the source with a blurry delivery copy." },
    ],
    related: [
      toolLink("Compress PDF", ROUTE_PATHS.compressPdf, "Measure actual savings across honest compression modes."),
      toolLink("Split PDF", ROUTE_PATHS.splitPdf, "Create smaller page ranges when one file cannot meet the limit."),
      toolLink("PDF attachment size study", ROUTE_PATHS.pdfAttachmentSizeStudy, "See how file bytes expand during email encoding."),
    ],
  },
  {
    ...published,
    id: "compress-pdf-for-email",
    kind: "search-guide",
    path: ROUTE_PATHS.compressPdfForEmailGuide,
    eyebrow: "Email attachment PDF guide",
    title: "How to compress a PDF for email and leave room for message overhead",
    seoTitle: "How to Compress a PDF for Email Attachments | PDFEnrich",
    metaDescription: "Compress a PDF for email, understand Base64 attachment overhead, preserve readable text, choose a safe target, and verify the exact file you attach.",
    lede: "The file size shown in your folder is not the whole email message. Attachment encoding adds about one-third before headers and message content, so leave margin instead of aiming at the provider ceiling.",
    facts: [["Encoding effect", "Base64 adds about one-third"], ["Best first choice", "Balanced compression"], ["Final test", "Attach the reopened download"]],
    primaryAction: toolLink("Compress a PDF for email", ROUTE_PATHS.compressPdf, "Create and compare a smaller browser-processed copy."),
    guideToolId: "compress-pdf",
    workedExample: {
      title: "Prepare a scan-heavy report for attachment",
      input: "A report opens correctly but is too large for a recipient's attachment policy.",
      action: "Create a smaller copy, keep text structure when possible, and choose a target below the stated message ceiling.",
      result: "The attached file should be the reopened verified copy, with enough margin for encoding and message headers.",
      caption: "Measured source and output bytes make the attachment decision visible.",
    },
    sections: [
      { heading: "1. Separate file size from message size", body: "Email systems commonly encode binary attachments as Base64 text. The encoded attachment is roughly four bytes for every three source bytes, before message headers and body content. Provider and organization limits vary, so check the recipient's current rule." },
      { heading: "2. Choose a target with margin", body: "Do not compress to the exact published ceiling. Leave space for encoding, filenames, MIME boundaries, signatures, and other attachments. For a strict workflow, send a test to yourself or use the organization's approved secure file-sharing path." },
      { heading: "3. Preserve readability and function", body: "Start with structure-preserving compression for reports, contracts, forms, and searchable records. Use flattened maximum reduction only when a visual copy is acceptable. Zoom into the smallest text and inspect image details before sending." },
      { heading: "4. Attach the file you actually verified", body: "Reopen the downloaded result, confirm page count and order, then attach that exact copy. If the message still exceeds the limit, split the PDF into named parts or use an approved sharing link rather than repeatedly damaging the document." },
    ],
    related: [
      toolLink("Compress PDF", ROUTE_PATHS.compressPdf, "Create a smaller verified delivery copy."),
      toolLink("PDF attachment size study", ROUTE_PATHS.pdfAttachmentSizeStudy, "Download measured Base64 overhead data."),
      toolLink("Compress a PDF to 1 MB", ROUTE_PATHS.compressPdfToOneMbGuide, "Work toward a fixed upload ceiling."),
    ],
  },
  {
    ...published,
    id: "combine-pdf-files-on-mac",
    kind: "search-guide",
    path: ROUTE_PATHS.combinePdfOnMacGuide,
    eyebrow: "Mac PDF combining guide",
    title: "How to combine PDF files on a Mac and verify the page order",
    seoTitle: "How to Combine PDF Files on Mac Online | PDFEnrich",
    metaDescription: "Combine PDF files on a Mac in your browser, arrange source files, preserve native pages, handle mixed page sizes, and verify every transition.",
    lede: "A Mac can merge PDFs without converting pages to screenshots. The important work is choosing the right source files, arranging them deliberately, and checking every boundary in the final packet.",
    facts: [["Runs in", "Safari, Chrome, and Edge on macOS"], ["Merge method", "Copies native PDF pages"], ["Review focus", "Order, transitions, and duplicates"]],
    primaryAction: toolLink("Combine PDFs on Mac", ROUTE_PATHS.mergePdf, "Choose files from Finder and arrange the final packet."),
    guideToolId: "merge-pdf",
    workedExample: {
      title: "Combine a proposal and three exhibits",
      input: "A proposal PDF and three exhibit PDFs are stored in one Finder folder.",
      action: "Add them in reading order, confirm each source page count, and merge native pages.",
      result: "The final PDF should begin with the proposal and preserve every exhibit transition without duplicates.",
      caption: "The merge workflow keeps source file order visible before export.",
    },
    sections: [
      { heading: "1. Prepare a clean Finder folder", body: "Move only the approved source PDFs into one folder and rename them with simple sequence numbers when order is ambiguous. Open each file in Preview or another reader to confirm page count, orientation, and that it is the correct version." },
      { heading: "2. Add and arrange the source files", body: "Choose the PDFs in Safari, Chrome, or Edge, then drag whole files into the final reading order. Each source keeps its internal page sequence. If pages inside one PDF are wrong, organize that file before the final merge." },
      { heading: "3. Keep native page quality", body: "A native merge copies PDF pages without taking screenshots, preserving selectable text, vectors, page dimensions, and embedded page content. Mixed portrait, landscape, letter, and A4 pages are valid, but check their scroll and print behavior." },
      { heading: "4. Verify the complete packet", body: "Confirm the final page count equals the sum of the sources. Inspect the first and last page and every transition where a new source begins. Save the merged download with a clear version name and keep the individual approved source files." },
    ],
    related: [
      toolLink("Merge PDF", ROUTE_PATHS.mergePdf, "Combine native PDF pages in your selected order."),
      toolLink("Organize PDF", "/organize-pdf", "Reorder or rotate pages inside one source."),
      toolLink("How to combine PDFs", ROUTE_PATHS.combinePdfGuide, "Use the full cross-platform packet checklist."),
    ],
  },
  {
    ...published,
    id: "sign-pdf-on-android",
    kind: "search-guide",
    path: ROUTE_PATHS.signPdfOnAndroidGuide,
    eyebrow: "Android PDF signing guide",
    title: "How to sign a PDF on Android with a typed or drawn signature",
    seoTitle: "How to Sign a PDF on Android Online | PDFEnrich",
    metaDescription: "Sign a PDF on Android in Chrome, type or draw a signature, add initials and dates, understand visual-signature limits, and verify the download.",
    lede: "A mobile signature should be placed only after the document is complete. Use a typed keyboard-accessible mark or draw carefully, then reopen the downloaded PDF before submitting it.",
    facts: [["Works in", "Chrome on Android"], ["Signature choices", "Type, draw, or upload"], ["Important limit", "No certificate identity verification"]],
    primaryAction: toolLink("Sign a PDF on Android", ROUTE_PATHS.signPdf, "Choose a PDF and place a visual self-signature."),
    guideToolId: "sign-pdf",
    workedExample: {
      title: "Sign and date a one-page approval",
      input: "An approval form needs one signature and today's date.",
      action: "Complete the date first, create a typed or drawn signature, zoom in, and place it on the line.",
      result: "The reopened download should show both marks at readable size without covering surrounding text.",
      caption: "The mobile signing workflow supports touch placement and verified PDF export.",
    },
    sections: [
      { heading: "1. Finish the document before signing", body: "Read every page and complete required text, dates, checks, and initials first. Keep the source copy. A signature should confirm the version you reviewed, not an incomplete draft." },
      { heading: "2. Choose the signature method", body: "Type your name for a fast keyboard-accessible signature, draw with a finger or stylus, or upload a tightly cropped image. A typed alternative is useful when precise drawing is difficult on a small screen." },
      { heading: "3. Place the mark at useful zoom", body: "Zoom into the signature line, place the mark, and resize it without covering labels or nearby clauses. Check every initials line separately. Switch out of the signing tool before scrolling long distances so the mark does not move accidentally." },
      { heading: "4. Understand and verify the result", body: "PDFEnrich places a visual self-attested signature; it does not issue a digital certificate, notarize identity, or create a third-party signing ceremony. Download the PDF, reopen it from Files or Downloads, and verify every page before submitting it." },
    ],
    related: [
      toolLink("Sign PDF", ROUTE_PATHS.signPdf, "Create and place a visual signature."),
      toolLink("Fill PDF", "/fill-pdf", "Add text, checks, dates, and initials before signing."),
      toolLink("Fill and sign guide", ROUTE_PATHS.fillAndSignPdfGuide, "Review signature boundaries and final checks."),
    ],
  },
  {
    ...published,
    id: "fill-pdf-without-adobe",
    kind: "search-guide",
    path: ROUTE_PATHS.fillPdfWithoutAdobeGuide,
    eyebrow: "Browser PDF form guide",
    title: "How to fill out a PDF without Adobe Acrobat",
    seoTitle: "How to Fill Out and Sign a PDF Without Adobe Acrobat | PDFEnrich",
    metaDescription: "Fill out and sign a PDF without Adobe Acrobat. Use interactive fields or add text, checks, dates, initials, and a signature online for free.",
    lede: "You do not need a desktop subscription to complete many PDF forms. First determine whether the document has interactive fields or a flat page, then use the workflow that preserves the clearest result.",
    facts: [["Interactive forms", "Use existing fields"], ["Flat forms", "Place answers on the page"], ["Account required", "No for supported browser tools"]],
    primaryAction: toolLink("Fill out a PDF", "/fill-pdf", "Choose a PDF and place answers without forced signup."),
    guideToolId: "sign-pdf",
    workedExample: {
      title: "Complete a flat application form",
      input: "A one-page application displays blank lines but contains no interactive fields.",
      action: "Place text over each line, add required checks and a date, then review alignment at normal zoom.",
      result: "The final PDF should reopen with each answer readable and every original label unobstructed.",
      caption: "Flat forms use positioned answers while interactive forms retain supported field values.",
    },
    sections: [
      { heading: "1. Test whether the form is interactive", body: "Click or tap a blank area. A visible cursor, checkbox, dropdown, or focus outline suggests an interactive AcroForm field. If nothing activates, the document may be a flat page that needs visually placed text and marks." },
      { heading: "2. Complete existing fields when available", body: "Use the form's text fields, checkboxes, radio options, and lists when supported. Keep answers within expected formats and watch for required fields. Do not flatten until you have reviewed whether the recipient needs editable field values." },
      { heading: "3. Place answers on flat forms carefully", body: "Zoom in and align each text box with its line or empty area. Use check marks only inside the intended boxes. Avoid covering prompts, legal wording, or nearby answers, and keep font size readable when the page returns to normal zoom." },
      { heading: "4. Review and submit the downloaded copy", body: "Read the form from the beginning, confirm names, dates, numbers, selections, initials, and signatures, then download and reopen it. Submit the exact verified copy and retain the source when your record policy requires it." },
    ],
    related: [
      toolLink("Fill PDF", "/fill-pdf", "Complete flat forms with positioned answers."),
      toolLink("PDF Form Filler", "/pdf-form-filler", "Use supported interactive PDF fields."),
      toolLink("Sign PDF on Android", ROUTE_PATHS.signPdfOnAndroidGuide, "Finish a form from an Android phone."),
    ],
  },
  {
    ...published,
    id: "convert-pdf-to-word-without-losing-formatting",
    kind: "search-guide",
    path: ROUTE_PATHS.pdfToWordWithoutFormattingLossGuide,
    eyebrow: "PDF to Word fidelity guide",
    title: "How to convert PDF to Word without losing the formatting you need",
    seoTitle: "Convert PDF to Word Without Losing Formatting | PDFEnrich",
    metaDescription: "Choose editable, OCR, or visual-fidelity PDF to Word conversion, understand unavoidable layout changes, and verify columns, tables, fonts, and page breaks.",
    lede: "No converter can promise perfect Word structure from every PDF. Choose the output mode based on what you need to edit, then review the layout zones most likely to change.",
    facts: [["Best for editing", "Editable reconstruction"], ["Best for scans", "OCR conversion"], ["Best appearance", "Visual-fidelity DOCX"]],
    primaryAction: toolLink("Convert PDF to Word", ROUTE_PATHS.pdfToWord, "Choose the layout mode that matches your next task."),
    guideToolId: "pdf-to-word",
    workedExample: {
      title: "Convert a two-column report",
      input: "A report contains headings, two text columns, a table, and fixed page breaks.",
      action: "Create an editable DOCX, then compare its reading order and table structure against the source.",
      result: "Useful text should remain editable, while ambiguous columns and table cells receive deliberate manual review.",
      caption: "PDF stores positioned page elements, while Word rebuilds a flowing document structure.",
    },
    sections: [
      { heading: "1. Define what formatting must survive", body: "List the elements that matter: editable paragraphs, headings, tables, columns, page breaks, fonts, images, or exact visual appearance. A mode optimized for editing cannot always preserve every positioned element exactly." },
      { heading: "2. Choose editable, OCR, or visual fidelity", body: "Use Editable for reusable text and normal document revision. Use OCR when the PDF pages are images. Choose Visual fidelity when matching the page appearance is more important than editing individual words, because page images can preserve appearance without reconstructing the original document model." },
      { heading: "3. Review known risk zones", body: "Compare multi-column reading order, wrapped table cells, headers, footers, footnotes, floating labels, custom fonts, and manual line breaks. PDF fragments that look connected on a page may not contain enough structure to rebuild the original Word layout automatically." },
      { heading: "4. Save a verified working copy", body: "Open the DOCX in the Word-compatible editor you plan to use, inspect each risk zone, and correct structure before distribution. Keep the original PDF as the reference and avoid presenting a reconstructed Word file as the untouched source." },
    ],
    related: [
      toolLink("PDF to Word", ROUTE_PATHS.pdfToWord, "Create editable, OCR, or visual-fidelity DOCX output."),
      toolLink("PDF to Word formatting guide", ROUTE_PATHS.pdfToWordGuide, "Compare the available conversion modes in detail."),
      toolLink("Edit a scanned PDF", ROUTE_PATHS.editScannedPdfGuide, "Prepare image-only pages with OCR."),
    ],
  },
  {
    ...published,
    id: "remove-pages-from-pdf",
    kind: "search-guide",
    path: ROUTE_PATHS.removePagesFromPdfGuide,
    eyebrow: "PDF page removal guide",
    title: "How to remove pages from a PDF without deleting the wrong version",
    seoTitle: "How to Remove Pages from a PDF Online | PDFEnrich",
    metaDescription: "Remove unwanted PDF pages in the browser, confirm page numbers and thumbnails, preserve the source, and verify the final sequence before sharing.",
    lede: "Page removal is easy to perform and easy to get wrong. Work on a copy, identify pages by content as well as number, and reopen the export before replacing or sharing anything.",
    facts: [["Safest habit", "Keep the original PDF"], ["Selection check", "Thumbnail and visible content"], ["Final proof", "Recount and reopen pages"]],
    primaryAction: toolLink("Remove PDF pages", "/delete-pdf-pages", "Choose unwanted pages and export the remaining sequence."),
    guideToolId: "split-pdf",
    workedExample: {
      title: "Remove a blank scan and duplicate receipt",
      input: "A 14-page packet contains one accidental blank page and one duplicated receipt.",
      action: "Identify both pages by thumbnail and visible content, remove them, and export the remaining pages.",
      result: "The verified copy should contain 12 pages in the original relative order with both unwanted pages absent.",
      caption: "Page tools operate on explicit page selections and preserve the remaining sequence.",
    },
    sections: [
      { heading: "1. Save the source and name the task", body: "Keep the original PDF unchanged. Write down what must be removed, such as an accidental blank scan, a duplicate, or an outdated appendix. Avoid relying only on page numbers when cover sheets or inserted pages may have shifted the sequence." },
      { heading: "2. Match thumbnails to visible content", body: "Use readable thumbnails and open uncertain pages at full size. Confirm headers, page numbers printed on the document, names, or other non-sensitive landmarks before marking a page for removal." },
      { heading: "3. Review the remaining sequence", body: "After choosing pages, check the pages immediately before and after every removal. Make sure a section does not begin mid-sentence, an attachment reference still points to the correct exhibit, and no required signature page was selected accidentally." },
      { heading: "4. Export, recount, and reopen", body: "Download the result, confirm the expected page count, and reopen it in another reader. Check the first page, last page, and every removal boundary. Share the verified copy under a new filename rather than overwriting the only source." },
    ],
    related: [
      toolLink("Remove pages from PDF", "/delete-pdf-pages", "Delete selected pages from a copied document."),
      toolLink("Organize PDF", "/organize-pdf", "Reorder, rotate, duplicate, or remove pages."),
      toolLink("Split PDF", ROUTE_PATHS.splitPdf, "Extract a page range into a separate PDF."),
    ],
  },
  {
    ...published,
    id: "rotate-pdf-and-save",
    kind: "search-guide",
    path: ROUTE_PATHS.rotatePdfAndSaveGuide,
    eyebrow: "Permanent PDF rotation guide",
    title: "How to rotate a PDF and save the page orientation permanently",
    seoTitle: "How to Rotate a PDF and Save It Permanently | PDFEnrich",
    metaDescription: "Rotate selected PDF pages, distinguish viewer rotation from saved page rotation, handle mixed orientations, and verify printing and export.",
    lede: "A reader can rotate only its current view without changing the file. To make the orientation travel with the PDF, rotate the selected pages and export a new saved copy.",
    facts: [["Viewer rotation", "May be temporary"], ["Saved rotation", "Exports page rotation"], ["Mixed documents", "Review each selected page"]],
    primaryAction: toolLink("Rotate and save PDF pages", "/rotate-pdf", "Select pages, rotate them, and export the corrected copy."),
    workedExample: {
      title: "Correct three sideways pages in a mixed scan",
      input: "A 20-page scan contains three landscape pages displayed sideways.",
      action: "Select only those pages, rotate them clockwise, and leave the remaining pages unchanged.",
      result: "The reopened export should display and print all 20 pages in their intended reading orientation.",
      caption: "Saved page rotation is verified after export instead of relying on a temporary viewer setting.",
    },
    sections: [
      { heading: "1. Check whether the file or viewer is rotated", body: "Rotate the page in your current reader, close the file, and reopen it. If the page returns sideways, the reader changed only its display. A permanent fix requires exporting page rotation into a new PDF." },
      { heading: "2. Select only the affected pages", body: "Use thumbnails to identify portrait pages, landscape pages, and scans captured upside down. Apply clockwise or counterclockwise rotation only to the intended selections. Recheck pages with charts or photographs whose correct top edge may not be obvious." },
      { heading: "3. Review mixed page dimensions", body: "Rotation changes orientation, not the underlying paper size. A landscape letter page remains a landscape letter page after the correct turn. Inspect page transitions and print preview when a document mixes letter, A4, portrait, and landscape content." },
      { heading: "4. Export and test permanence", body: "Download the corrected PDF, reopen it in a second reader, and revisit each rotated page. Confirm page count, reading direction, thumbnails, and print orientation. Keep the source when document history matters." },
    ],
    related: [
      toolLink("Rotate PDF", "/rotate-pdf", "Apply saved rotation to selected pages."),
      toolLink("Organize PDF", "/organize-pdf", "Review rotation alongside page order."),
      toolLink("Remove PDF pages", ROUTE_PATHS.removePagesFromPdfGuide, "Clean unwanted pages from the same copied document."),
    ],
  },
]);

export const PDF_ATTACHMENT_SIZE_STUDY = Object.freeze({
  ...published,
  id: "pdf-attachment-size-study",
  kind: "study",
  path: ROUTE_PATHS.pdfAttachmentSizeStudy,
  eyebrow: "Reproducible PDF attachment study",
  title: "What a PDF attachment weighs after email encoding",
  seoTitle: "PDF Email Attachment Size and Base64 Overhead Study | PDFEnrich",
  metaDescription: "Download a reproducible dataset measuring raw and Base64-encoded sizes for seven public PDF fixtures, with page counts, methods, limitations, and email guidance.",
  lede: "A PDF's folder size is not its full email footprint. We measured seven public fixtures byte-for-byte before and after standard Base64 encoding so attachment planning can use reproducible numbers.",
  facts: [["Public fixtures", "7"], ["Observed overhead", "33.33% to 34.94%"], ["Method", "Raw bytes versus RFC 4648 Base64"]],
  primaryAction: toolLink("Compress a PDF for email", ROUTE_PATHS.compressPdf, "Measure a real file and create a smaller verified copy."),
  sections: [
    { heading: "Methodology", body: "Each fixture was read as raw bytes and encoded with standard RFC 4648 Base64. We recorded the source byte count, encoded byte count, percentage increase, and parseable page count where available. The malformed fixture and password-protected fixture remain in the set because email transport encodes bytes whether or not a reader can open them without recovery information." },
    { heading: "What the numbers mean", body: "Base64 represents every three source bytes with four encoded characters, with small rounding effects for files whose byte count is not divisible by three. The measured fixtures therefore grew by about one-third before MIME boundaries, filenames, message headers, body content, signatures, or other attachments." },
    { heading: "How to plan an attachment target", body: "Do not aim at the exact message ceiling. Provider, plan, recipient, and organization policies vary, and some systems measure the entire encoded message. Leave margin, verify the current recipient rule, and use an approved sharing workflow when compression would make the PDF unreadable." },
    { heading: "Limitations and reproducibility", body: "Seven synthetic fixtures do not represent every PDF or every mail system. The study measures encoding overhead, not delivery success, spam filtering, provider limits, or compression quality. Download the CSV, JSON method record, and source fixtures to repeat or extend the calculation." },
  ],
  matrix: {
    caption: "Measured raw and Base64-encoded fixture sizes",
    columns: ["Fixture", "Raw bytes", "Base64 bytes", "Increase", "Pages"],
    rows: [
      ["Complex layout", "3,611", "4,816", "33.37%", "2"],
      ["Encrypted sample", "2,977", "3,972", "33.42%", "Password required"],
      ["Large progressive", "154,441", "205,924", "33.34%", "100"],
      ["Malformed recovery", "83", "112", "34.94%", "Not parseable"],
      ["Clean scan", "129,801", "173,068", "33.33%", "1"],
      ["Degraded scan", "147,071", "196,096", "33.33%", "1"],
      ["Simple searchable", "2,583", "3,444", "33.33%", "2"],
    ],
  },
  downloads: [
    ["Attachment-size dataset (CSV)", "/research/attachment-size/pdf-attachment-size-study.csv", "Seven fixtures with raw bytes, encoded bytes, overhead, and page counts"],
    ["Method and results (JSON)", "/research/attachment-size/pdf-attachment-size-study.json", "Machine-readable scope, formula, observations, and limitations"],
    ["Public benchmark fixtures", "/research/fixtures/simple-searchable.pdf", "Start with the smallest two-page searchable fixture"],
  ],
  sources: [
    ["RFC 4648: Base-N Encodings", "https://datatracker.ietf.org/doc/html/rfc4648"],
  ],
  related: [
    toolLink("Compress PDF for email", ROUTE_PATHS.compressPdfForEmailGuide, "Use the measured overhead when choosing a delivery target."),
    toolLink("Compress PDF", ROUTE_PATHS.compressPdf, "Compare actual source and output file sizes."),
    toolLink("Browser PDF benchmark", ROUTE_PATHS.pdfBenchmark, "Download the full public fixture set and release methodology."),
  ],
});
